### ISSUE TITLE
Fix results e2e, failing due to PSA

### ISSUE THREAD

**Issue by sm43** [tektoncd/operator#1148]
due to PSA in pipelines, results deployment is failing
    but adding restriced fields also doesn't work
    ```
    Error: container has runAsNonRoot and image will run as root
    (pod: "tekton-results-postgres-0_tekton-pipelines(a7492fa3-e313-4fb7-ae69-9b0a4e14d557)", container: postgres)
    ```
    so need to check in results.

**Comment by vdemeester** [comment]
We probably need to use a `runAsUser` in the spec then.
