### ISSUE TITLE
Adds new feature flags added in pipeline in Operator 

### ISSUE THREAD

**Issue by sm43** [tektoncd/operator#1152]
there are 2 new fields added in pipelines feature flag configmap
https://github.com/tektoncd/pipeline/blob/b16a5b5ea65a4dae2401415fb498c340170557c2/config/config-feature-flags.yaml#L84
```
  # Setting this flag to "enforce" will enforce verification of tasks/pipeline. Failing to verify
  # will fail the taskrun/pipelinerun. "warn" will only log the err message and "skip"
  # will skip the whole verification
  resource-verification-mode: "skip"
  # Setting this flag to "true" enables populating the "provenance" field in TaskRun
  # and PipelineRun status. This field contains metadata about resources used
  # in the TaskRun/PipelineRun such as the source from where a remote Task/Pipeline
  # definition was fetched.
  enable-provenance-in-status: "false"
```
which are yet to be added and exposed though TektonConfig so that user can configure those.

**Comment by sm43** [comment]
Example https://github.com/tektoncd/operator/commit/7935a730772c65ffc464b9f05ea0d4582cf527fb

TODO for this feature:
* define fields here https://github.com/tektoncd/operator/blob/e1913c2e76edf4bd6a69f19547ef1ec8a51bd853/pkg/apis/operator/v1alpha1/tektonpipeline_types.go#L87
* run ./hack/update-codegen
* add validation for those fields
* add defaulting for those fields
* and test :P

**Comment by sm43** [comment]
will be in pipelines 0.42 so we have a little time to add them

**Comment by PuneetPunamiya** [comment]
Closing this issues as this is addressed in this patch https://github.com/tektoncd/operator/pull/1194

/close
