### ISSUE TITLE
How to smoothly upgrade tekton

### ISSUE THREAD

**Issue by garyyang85** [tektoncd/operator#1252]
Sorry for the dupe, I just open a discussion here, but seems it is not the right place.

This should be a general question. I use the "oc apply -f " command to install tekton 0.59 on openshift. Now I need a new function in tknton 0.63. How can I smoothly upgrade?
I can delete the 0.59 first to use the "oc delete -f ", but this will delete all the resources like pipeline / pipelinerun / task. Is there a way to not delete these resources and upgrade to another version? Thanks.

**Comment by vdemeester** [comment]
@garyyang85 it is the right place, it's just a matter of time maintainers have to answer discussions 😅
