### ISSUE TITLE
Tasks that Run Rodman (and possibably other container tools) Fail

### ISSUE THREAD

**Issue by acornett21** [tektoncd/operator#1287]
# Expected Behavior
I'd expect `Tasks` that run podman pods (and podman comands in said pod) would be able to run without any issue. This used to work prior to the below PR:
- #1149 

# Actual Behavior
Any `podman` command that is executed fails and causes the task to fail
```
+ podman pull image-registry.openshift-image-registry.svc:5000/oco/certified-operator-index:v4.12
time="2023-01-20T17:35:09Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
time="2023-01-20T17:35:09Z" level=error msg="running `/usr/bin/newuidmap 35 0 1000 1 1 10000 5000`: newuidmap: write to uid_map failed: Operation not permitted\n"
Error: cannot set up namespace using "/usr/bin/newuidmap": exit status 1
```

# Steps to Reproduce the Problem

1. Install the Latest version of Pipelines Operator on OpenShift (4.12 is where I see this 1.9.0 version, but could be in other versions).
2. Create a Tekton Task that uses podman pod.
3. Try to run `podman info` (or any other podman cmd) and see this fail.

# Additional Info

- Kubernetes version:
  ```
  Client Version: 4.12.0
  Kustomize Version: v4.5.7
  Server Version: 4.12.0
  Kubernetes Version: v1.25.4+77bec7a

  ```

- Tekton Pipeline version:
  ```
  {"packageName":"openshift-pipelines-operator-rh","version":"1.9.0"}
  ```

This is breaking pipelines/tasks that are a part of Red Hat certification process when run on a partners own cluster, so we'd like this to be merged/released on priority.

**Comment by ArthurVardevanyan** [comment]
I ran into a similar issue in my testing with buildah

```log
time="2023-01-21T19:00:00Z" level=warning msg="running newgidmap: exit status 1: newgidmap: write to gid_map failed: Operation not permitted\n"
time="2023-01-21T19:00:00Z" level=warning msg="Falling back to single mapping"
time="2023-01-21T19:00:00Z" level=warning msg="Error running newuidmap: exit status 1: newuidmap: write to uid_map failed: Operation not permitted\n"
time="2023-01-21T19:00:00Z" level=warning msg="Falling back to single mapping"
STEP 1/20: FROM debian:bookworm-slim
Resolved "debian" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/debian:bookworm-slim...
Getting image source signatures
Copying blob sha256:b37cbf60a964400132f658413bf66b67e5e67da35b9c080be137ff3c37cc7f65
time="2023-01-21T19:00:02Z" level=error msg="While applying layer: ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/gshadow): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /etc/gshadow: invalid argument exit status 1"
Error: creating build container: copying system image from manifest list: writing blob: adding layer with blob "sha256:b37cbf60a964400132f658413bf66b67e5e67da35b9c080be137ff3c37cc7f65": ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/gshadow): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /etc/gshadow: invalid argument exit status 1
```

I was able to workaround it with the changes below.

With old scc
```
image: quay.io/buildah/stable:v1.27.0
runAsUser: 1000  # (65532 non image building tasks)
runAsNonRoot: true # or false (not used)
allowPrivilegeEscalation: true  # or false (non image building tasks)
```
With new scc
```
image:  registry.access.redhat.com/ubi9/buildah:9.1.0-5
runAsUser: 0  # (65532 non image building tasks)
runAsNonRoot: false # or true, (non image building tasks)
allowPrivilegeEscalation: false  # or false 
```

Not sure which scenario is considered more secure.

**Comment by acornett21** [comment]
@ArthurVardevanyan Your first example is more secure, you shouldn't run containers as `root` user, especially for applications that are running on production clusters.

**Comment by ArthurVardevanyan** [comment]
> @ArthurVardevanyan Your first example is more secure, you shouldn't run containers as `root` user, especially for applications that are running on production clusters. 

In that case, in addition to reverting privilege escalation, shouldn't the SCC also be modified to prevent this.

**Comment by acornett21** [comment]
I said 'shouldn't not 'can't', there are cases where root is the only option, but this isn't one tekton should dictate IMO. Also all of the documents for `pipelines-scc` point to it being a copy of `anyuid` SCC which also has `RunAsAny`.

**Comment by ibotty** [comment]
What's the way forward?  This is still not working.

**Comment by vdemeester** [comment]
So for information, there is some fix in 4.12 that should help us run "user namespace" containers way more reliably. What this mean, is technically, it should be possible, to run "as root in the container and as user on the node" with the default `restricted` scc. This should also make running `podman` a bit more easily.

*That said*, running a container runtime in a container securely (not as root, with almost no extra privileges) is very trick and prone to weird behavior. 
And the operator aims to not provide "unsecure" things as much as possible. Today, it is definitely possible to run `podman` as root, with or without `privileged` in the cluster ; but this is and might not be something the operator will enable it by default ; this would be on the user to decide *explicitely* to run something less secure.

I think there is two ways forward (to be done in parallel) :
- Document how to run `podman` in a Pipeline in a reliable way (creating the `SCC`, `SA`, … required, …)
- Look into the latest 4.12 and see if the recent fixes helps us cover ~90% of use cases with the `default` SA and `restricted` SCC

**Comment by acornett21** [comment]
> * Look into the latest 4.12 and see if the recent fixes helps us cover ~90% of use cases with the `default` SA and `restricted` SCC

In 4.12 by default workloads get the `restricted-v2` scc, which has `allowPrivilegeEscalation: false`, which would cause the same issue as the `pipeline` scc that this tekton operator provides and uses to run tasks. To me, this would still not work, unless the PR opened is accepted (which the maintainers said they won't accept, which is fine), and the only option is that the user of tekton creates a custom SA and SCC to run their workloads.

**Comment by vdemeester** [comment]
> In 4.12 by default workloads get the `restricted-v2` scc, which has `allowPrivilegeEscalation: false`, which would cause the same issue as the `pipeline` scc that this tekton operator provides and uses to run tasks. To me, this would still not work, unless the PR opened is accepted (which the maintainers said they won't accept, which is fine), and the only option is that the user of tekton creates a custom SA and SCC to run their workloads.

Yes, but 4.12 also ships with something called userns, where you can actually run something with `restricted-v2` but *still* be root in the container (and a random uid on the node where that container is). This works *today* but it had a bug where we would appear as root but could do "root" thing inside (like `dnf install …`, …) and thus you wouldn't be able to run `podman` either. Most recent nightly have a fix for this.

But yes, in general, the only option is that the user of tekton creates a custom SA and SCC to run their workloads. [TEP-0085](https://github.com/tektoncd/community/blob/main/teps/0085-per-namespace-controller-configuration.md) would help making this "bearable" (aka less verbose) for users 👼🏼

> Look into the latest 4.12 and see if the recent fixes helps us cover ~90% of use cases with the `default` SA and `restricted` SCC

I am preparing something on this (a doc/blog/…)

**Comment by pbaity** [comment]
@vdemeester Any update on that doc or blog? I _think_ I'm hitting this same issue, and I'd like to try out that option of creating a custom SA and SCC, but want to understand the right way to do it.

Just for clarity, I'm using the `buildah` Task from the Tekton Catalog, which [specifies `securityContext.privileged: true`](https://github.com/tektoncd/catalog/blob/main/task/buildah/0.5/buildah.yaml#L91-L92), and I'm getting this mouthful of an error (which I've added spacing to for readability):

```
failed to create task run pod "pipelinerun-8pmqk-buildah": pods "pipelinerun-8pmqk-buildah-pod" is forbidden: unable to validate against any security context constraint: 

[
    provider "anyuid": Forbidden: not usable by user or serviceaccount,
    spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed,
    provider "restricted": Forbidden: not usable by user or serviceaccount,
    provider "nonroot-v2": Forbidden: not usable by user or serviceaccount,
    provider "pcap-dedicated-admins": Forbidden: not usable by user or serviceaccount,
    provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount,
    provider "elasticsearch-scc": Forbidden: not usable by user or serviceaccount,
    provider "log-collector-scc": Forbidden: not usable by user or serviceaccount,
    provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount,
    provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount,
    provider "hostnetwork": Forbidden: not usable by user or serviceaccount,
    provider "hostaccess": Forbidden: not usable by user or serviceaccount,
    provider "splunkforwarder": Forbidden: not usable by user or serviceaccount,
    provider "node-exporter": Forbidden: not usable by user or serviceaccount,
    provider "privileged": Forbidden: not usable by user or serviceaccount
]. 

Maybe missing or invalid Task my-namespace/
```

If I copy the `buildah` Task and modify the SCC to `privileged: false`, it gives a different error. I've tried several different SCC configurations mentioned in this issue and elsewhere, but they also give the same error:

```
Error: error writing "0 0 4294967295\n" to /proc/22/uid_map: write /proc/22/uid_map: operation not permitted
time="2023-03-15T14:57:02Z" level=error msg="error writing \"0 0 4294967295\\n\" to /proc/22/uid_map: write /proc/22/uid_map: operation not permitted"
time="2023-03-15T14:57:02Z" level=error msg="(unable to determine exit status)"
```

**Comment by acornett21** [comment]
@pbaity That is in fact the same issue/error. 

The custom scc would look like this:
```
oc apply -f - <<'EOF'
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubernetes.io/description: my-custom-scc is a close replica of pipeline scc with privilege escalation.
    release.openshift.io/create-only: "true"
  name: my-custom-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
  - SETFCAP
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups:
  - system:cluster-admins
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
 EOF
 ```
 
 You could then attach it to your SA that runs the pipeline by doing this:
 ```
 oc adm policy add-scc-to-user my-custom-scc -z the-service-account-that-runs-the-pipeline
 ```
 
 This would be the quickest way to accomplish this, there are other ways as well. Hopefully this works for you.

**Comment by pbaity** [comment]
@acornett21 Thanks! That worked for me, and saved a lot of time.
