### ISSUE TITLE
Add support for specifying replicas and resources for deployment

### ISSUE THREAD

**Issue by yuzp1996** [tektoncd/operator#1293]
### Feature request

When deploying Tekton using the operator I want to specify replicas and resource requests and limits for deployment so that I can easily resolve SPOF and OOM issues.
### Use case

1. To enable HA for Tekton I need to specify more than one replica for deployment.
2. If the resource request is beyond the limit then the pod will OOM and I need to scale the operator's replica to 0 and change the deployment resource manually.

**Comment by piyush-garg** [comment]
This looks like same as #1037
