### ISSUE TITLE
The cluster-admin privileges for tekton-dashboard-extensions

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/operator#131]
When installing the addon dashboard v0.8.2, we come across the following error:

```
'clusterroles.rbac.authorization.k8s.io "tekton-dashboard-extensions" is forbidden: must have cluster-admin privileges to use the aggregationRule'
```

**Comment by nikhil-thomas** [comment]
temporary fix 
https://github.com/tektoncd/operator#prerequisite

provide cluster-admin role to operator serviceaccount
```
kc create clusterrolebinding tekton-operator-cluster-admin --clusterrole cluster-admin --serviceaccount tekton-operator:tekton-operator
```

we will handle it with a better fix soon.

**Comment by eddycharly** [comment]
did you try to add the `list` verb for clusterroles in the operator cluster role ?

**Comment by eddycharly** [comment]
ping @nikhil-thomas

**Comment by 06kellyjac** [comment]
still important

**Comment by 06kellyjac** [comment]
Did #174 resolve this or does this still need work?

**Comment by rlandesman** [comment]
Just a heads up that I ran into the same issue when applying the operator to my cluster:

```text
"Install failed with message: clusterroles.rbac.authorization.k8s.io \"tekton-dashboard-extensions\" is forbidden: must have cluster-admin privileges to use the aggregationRule"},{"type":"Ready","status":"False","lastTransitionTime":"2021-04-28T18:30:27Z","reason":"Error","message":"Install failed with message: clusterroles.rbac.authorization.k8s.io \"tekton-dashboard-extensions\" is forbidden: must have cluster-admin privileges to use the aggregationRule"}]}
```

**Comment by nikhil-thomas** [comment]
true, so far we have been manually removing the aggregate rule from dashboard release.yaml. it is temporary fix. we need a better solution like your suggestion.

**Comment by AlanGreene** [comment]
I propose we just remove the offending ClusterRole from the Dashboard's default installs. It is only required for users with Dashboard extensions and can be documented as an additional requirement when adding an extension.

https://github.com/tektoncd/dashboard/issues/2047

**Comment by nikhil-thomas** [comment]
At present, we are manually removing the clusterrole and rolebinding.
If it is alright to install the dashboard without them (default installs) by the operator,
then we can add a tiny filter in the operaotrs dashboard logic to filter those 2 out.

**Comment by 06kellyjac** [comment]
Can this issue be frozen open please
