### ISSUE TITLE
Add approaches to help override configmap with operators

### ISSUE THREAD

**Issue by yuzp1996** [tektoncd/operator#1346]
### Feature request

I want to configure some configurations that exists in configmap with the operator.

### Use case

For example, if I want to adjust log level I have to stop tekton-operator and make change in configmap config-logging.
If tekton-operator starts the config-logging will be revert.

**Comment by vdemeester** [comment]
I think this is covered by the `options` field, see https://github.com/tektoncd/operator/blob/main/docs/TektonConfig.md#additional-fields-as-options.
