### ISSUE TITLE
Update go version

### ISSUE THREAD

**Issue by Avni-Sharma** [tektoncd/operator#138]
Go version can be updated in https://github.com/tektoncd/operator/blob/master/go.mod#L26

**Comment by nikhil-thomas** [comment]
definitely :+1: 
our new developments will be in our [main](https://github.com/tektoncd/operator/tree/main) branch (knative/pkg based instead of operator-sdk)
https://github.com/tektoncd/operator/blob/8d57de69f9ac6b10fd807fe16899bfbf9e7039fa/go.mod#L5

**Comment by nikhil-thomas** [comment]
handled in the `main` (current default) branch of this repository.
https://github.com/tektoncd/operator/blob/f56fc17cf105c39186fedec2fe1cac011472e0cd/go.mod#L21
