### ISSUE TITLE
OpenShift operator installation failed

### ISSUE THREAD

**Issue by devopski** [tektoncd/operator#1386]
# Expected Behavior
Operator installed successfully via HELM
# Actual Behavior
`Error: INSTALLATION FAILED: clusterroles.rbac.authorization.k8s.io "tekton-operator" already exists`

# Steps to Reproduce the Problem

`helm install tekton-operator \
  -n openshift-operators \
  --set openshift.enabled=true \
  --set installCRDs=true \
  ./operator/chart
`

# Additional Info
![image](https://user-images.githubusercontent.com/77720864/225692599-bd050334-2d34-4a95-9bfd-6c58d8a9f238.png)

**Comment by jacksgt** [comment]
The cluster in which you are installing the Tekton Operator Helm chart already has a "tekton-operator" ClusterRole (maybe this is a left-over from a previous installation attempt).

You can remove the resources with:
```
oc delete clusterrole/tekton-operator clusterrolebinding/tekton-operator
```

Then re-try your `helm install` command.
