### ISSUE TITLE
OKD/OCP Event Listener Security Context : Unable to start due to explicit: runAsUser

### ISSUE THREAD

**Issue by ArthurVardevanyan** [tektoncd/operator#1421]
# Expected Behavior

For OpenShift, in order to start a pod with SCC ```restricted-v2```, ```runAsUser``` should not be set:
```yaml
runAsUser: 65532
```

# Actual Behavior

Link: https://github.com/tektoncd/triggers/blob/release-v0.23.x/pkg/reconciler/eventlistener/resources/container.go#L54
Link: https://github.com/tektoncd/operator/releases/tag/v0.66.0

Photo:
![image](https://user-images.githubusercontent.com/21159051/229502908-e0985056-01d1-4ff3-92c4-8d0503fd2495.png)

# Steps to Reproduce the Problem

1. Incept OKD/OCP 4.12
2. Install Tekton Operator v0.66.0 /w ```openshift-release.yaml```
3. Create an Event Listener

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

Server Version: 4.12.0-0.okd-2023-04-01-051724
Kubernetes Version: v1.25.0-2786+eab9cc98fe4c00-dirty

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

v0.45.0

**Comment by savitaashture** [comment]
Hi @ArthurVardevanyan We have fixed this issue in Triggers v0.23.1 as well as main branch
Here is the PR https://github.com/tektoncd/triggers/pull/1565 for reference


This fix will be available in next Operator patch/minor release

cc @vdemeester @piyush-garg

**Comment by lindy63** [comment]
Hi @savitaashture , could I trouble you to check if this is the same root cause seen when just installing the operator into an OKD 4.12 cluster (ie before trying to create anything else)?

On both the `tekton-operator-proxy-webhook` and the 'tekton-pipelines-controller' deployments I get the same error as @ArthurVardevanyan does above

![image](https://user-images.githubusercontent.com/61848016/231136649-4c2b535f-1837-499c-8c09-2d0bef279db3.png)

![image](https://user-images.githubusercontent.com/61848016/231137029-310d6507-62dd-448f-ac00-b6e7570fb2a0.png)

If it's not, please feel free to ignore me! :-)

**Comment by vdemeester** [comment]
@lindy63 it's probably not the same issue. @lindy63 which release yaml do you install ?

**Comment by lindy63** [comment]
Thanks @vdemeester, I just used the latest as per [this](https://github.com/tektoncd/operator/blob/main/docs/install.md)

**Comment by vdemeester** [comment]
@lindy63 you probably need to use the openshift one (so https://github.com/tektoncd/operator/releases/download/v0.66.0/openshift-release.yaml or https://storage.googleapis.com/tekton-releases/operator/latest/openshift-release.yaml)

**Comment by lindy63** [comment]
ah yes that worked right away! sorry, rookie error :-)

Thanks very much for the swift response @vdemeester  and sorry for the thread derailment!

**Comment by ibotty** [comment]
Is there a workaround until the new operator is released?

**Comment by ArthurVardevanyan** [comment]
Fixed: https://github.com/tektoncd/operator/releases/tag/v0.67.0

![image](https://github.com/tektoncd/operator/assets/21159051/7b09cb7e-c0b8-4030-986c-3428391d0c83)
