### ISSUE TITLE
OKD/OCP Tekton Resource Pruner: Unable to start due to explicit: runAsUser 

### ISSUE THREAD

**Issue by ArthurVardevanyan** [tektoncd/operator#1422]
# Expected Behavior

For OpenShift, in order to start a pod with SCC ```restricted-v2```, ```runAsUser``` should not be set:
```yaml
runAsUser: 65532
```

# Actual Behavior

Link: https://github.com/tektoncd/operator/blob/main/pkg/reconciler/common/prune.go#L343
Link: https://github.com/tektoncd/operator/releases/tag/v0.66.0

Photo:
![image](https://user-images.githubusercontent.com/21159051/229505954-6f7329c9-33b5-4142-b468-c54470a1e408.png)

# Steps to Reproduce the Problem

1. Incept OKD/OCP 4.12
2. Install Tekton Operator v0.66.0 /w ```openshift-release.yaml```
3. Create an Tekton Pipleine Pruner Resource

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

Server Version: 4.12.0-0.okd-2023-04-01-051724
Kubernetes Version: v1.25.0-2786+eab9cc98fe4c00-dirty

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

v0.45.0

**Comment by savitaashture** [comment]
cc @jkandasa
