### ISSUE TITLE
[OpenShift] occasionally addons installerset reconcilation stopped 

### ISSUE THREAD

**Issue by jkandasa** [tektoncd/operator#1441]
version 1.10.0 (v0.65.x)

in OpenShift, while running TektonConfigDeployment e2e tests, sometimes(not always) addons installerset reconciliation stopped working.
workaround: restarting the operator fixes the issue
one of the error message,
```
addon-versioned-clustertasks-1.10-9j7m7          False   Install failed with message: no matches for kind "ClusterTask" in version "tekton.dev/v1beta1"
```

**Comment by vdemeester** [comment]
Interesting, maybe the code should "wait"/"force next reconciliation" until the pipeline CRD are available.. maybe there can be a race where it starts too quickly ? 🤔

**Comment by vdemeester** [comment]
I'll go ahead and close this one. If it happens again, we'll create a new issue.
