### ISSUE TITLE
Tekton ConfigMaps are overwritten by Operator

### ISSUE THREAD

**Issue by bkmeneguello** [tektoncd/operator#149]
# Expected Behavior

After installing the Operator and make any modification to Tekton ConfigMaps (config-defaults, feature-flags) they should not be modified, even after operator restarts or upgrades.

# Actual Behavior

If I restart the operator deployment container the config-maps are overwritten with default values, replacing anything I've defined.

# Steps to Reproduce the Problem

- Install Tekton Operator
- Wait for everything to be provisioned
- Modify any tekton-pipelines/feature-flags config map entry
- Scale-down tekton operator deployment to zero
- Scale-up tekton operator deployment to one
- Check the modified tekton-pipelines/feature-flags config map is overwritten

**Comment by vdemeester** [comment]
/cc @nikhil-thomas 
/kind feature

I am not sure I agree with "should not be modified, even after operator restarts or upgrades.", **but** we should definitely keep the users modifications ; by merging the "current" one — modified by the user — and the new ones (that may contain some default values required by new versions).

**Comment by bkmeneguello** [comment]
I have no problem with non-destructive modifications, it is OK for my use-case.

**Comment by vincent-pli** [comment]
@vdemeester 
In `Knative/operator`, they supplied operators own api to handle this:
https://github.com/knative/operator/issues/264


I think we can borrow the idea.

**Comment by NissesSenap** [comment]
Is there any plans to manage the feature-flags cm through the operator or will that be keept as is?

**Comment by nikhil-thomas** [comment]
https://github.com/tektoncd/operator/pull/314
