### ISSUE TITLE
Could anyone create a new release from Tekton Operator?

### ISSUE THREAD

**Issue by eirisdg** [tektoncd/operator#1494]
Hi.

We are trying to user the Tekton Operator Helm Chart but we are having a problem with Kaniko in the Tekton Pipeline version that is included in the release 0.66 of Tekton Operator.

The issue is https://github.com/tektoncd/catalog/issues/1158
The fix is to upgrade Tekton Pipelines to v0.47.0

We have been trying to create a new release with the changes to fix it, but we have seen that many people are having problems to create new releases.
#1330 

Please, could anyone create a new Tekton Operator release with the changes included in the main branch and a new version in Tekton Operator Helm chart?

**Comment by piyush-garg** [comment]
Operator v0.67.0 just released with pipeline v0.47.0. Thanks
