### ISSUE TITLE
Separate API and Recinciler for Tektoncd Projects (Components)

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/operator#150]
# Why

Using the same API (`tektonaddons`) and its reconciler for all Tekton components (triggers, dashboard etc) makes it difficult to run, automate upgrade tests. It is difficult to add component specific upgrade logic in the reconciler,  each time we add a newer version of a component.

In addition, different components might support different install mode and/or watch modes. Eg: dashboard supports an features like `TENANT_NAMESPACE` with dashboard [install script](https://github.com/tektoncd/dashboard/blob/master/docs/install.md#installing-with-the-installer-script).

# Current Situation

The operator provides 2 APIs:
- `tektonpipelines.operator.tekton.dev`
- `tektonaddon.operator.tekton.dev`

There are 2 separate reconcilers to reconcile, 1 for tektonpipeline, and 1 for tektonaddon. The tektonaddon reconciles installation, updation and deletion of all the tekton components.

# Proposed Solution

Add new APIs
- tektontriggers.operator.tekton.dev
- tektondashboard.operator.tekton.dev
- tektonexperimental.operator.tekton.dev (will function like the current `tektonaddon` API)

Add separate controllers for the additional API to handle component specific operational logic and customizations.

# Additional Info

ref: knative/operator

Knative Operator handles Knative Serving and Knative Eventing using 2 separate set of APIs and reconcilers.
However, the 2 APIs and reconcilers do reuse code for common [API specs](https://github.com/knative/operator/tree/master/pkg/apis/operator/v1alpha1) and [reconcile logic](https://github.com/knative/operator/tree/master/pkg/reconciler).

**Comment by savitaashture** [comment]
Based on [slack](https://tektoncd.slack.com/archives/CKZQUT3MH/p1600361722021300) and WG conversation we will be implementing separate CRD for each addons as described in issue description for `main` branch where knative/pkg based refactoring of tektoncd/operator is going on

/assign

**Comment by nikhil-thomas** [comment]
we have TektonConfig, TektonPipeline, TektonTriggers, TektonDashboard and TektonAddons. Each of the CRDs have separate reconcilers.
Hence, closing this issue.

https://github.com/tektoncd/operator/pull/153
https://github.com/tektoncd/operator/pull/159
https://github.com/tektoncd/operator/pull/167
https://github.com/tektoncd/operator/pull/179
https://github.com/tektoncd/operator/pull/143
