### ISSUE TITLE
Post upgrade to 0.67.0 version of the operator - All pipeline runs are being marked as Failed with PipelineRunTimeout status

### ISSUE THREAD

**Issue by srisek** [tektoncd/operator#1543]
# Expected Behavior

Updated version of tekton dashboard to 0.35.0 along with the operator upgrade from v0.66.0. Changed all the existing pipeline run status to Failed and marked it as "PipelineRunTImeout"

# Actual Behavior

Dashboard has changed the status of all the pod status from "Succeeded" to "PipelineRunTimeOut" for the current pipeline runs and for the historical pipeline runs.

# Additional Info

![image](https://github.com/tektoncd/operator/assets/99493868/67185257-1580-4cdd-8813-dbe4b0ae1d65)

- Kubernetes version:

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-05-12T19:03:40Z", GoVersion:"go1.20.3", Compiler:"gc"
, Platform:"linux/amd64"}

- Tekton Pipeline version: v0.47.0
- Tekton Dashboard version : 0.35.0
- Triggers version: v0.24.0

**Comment by srisek** [comment]
Thanks can the operator be updated with a release to get the tekton-pipelines v0.48.0

**Comment by AlanGreene** [comment]
@tektoncd/operator-maintainers ☝️

**Comment by srisek** [comment]
Thanks @AlanGreene

**Comment by vdemeester** [comment]
Nightly is, but we need to do an operator release indeed.
cc @jkandasa

**Comment by leoffj** [comment]
Would really love to see a new operator release as well

**Comment by brovoca** [comment]
Please release a patch for the operator that bumps the pipelines version to at least v0.47.1.

**Comment by brovoca** [comment]
@vdemeester Can anything be done about this?

**Comment by viniagostini** [comment]
@vdemeester @jkandasa do you have a time frame for this patch?
I am facing the same bug from Pipelines 0.47.0 as other folks on this issue.

**Comment by jkandasa** [comment]
@viniagostini there is a new operator release planned by this week.

**Comment by brovoca** [comment]
This is taking a bit too long to resolve I think.

**Comment by jkandasa** [comment]
@viniagostini due to other issues to go on this release, we couldn't schedule the release on this week. hopefully by next week. 
Sorry for the delay.

**Comment by jkandasa** [comment]
Tekton Operator release v0.68.0 "Rock Sparrow" is out :tada:
https://github.com/tektoncd/operator/releases/tag/v0.68.0

**Comment by jkandasa** [comment]
@viniagostini does your issue resolved on `v0.68.0`?

**Comment by brovoca** [comment]
I can at least confirm that it's solved for me.

**Comment by cmorinupgrade** [comment]
Solved in 0.68.0. Issue should be closed.
