### ISSUE TITLE
Build an official image for Operator

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/operator#16]
# Expected Behavior
End user do not need build image themself if no specific requirement.
# Actual Behavior
Must build image for Operator
# Additional Info
As @nikhil-thomas comment here: https://github.com/tektoncd/operator/pull/15#discussion_r312363208
I think we need supply a official image for end user before we turn to `ko` (maybe)

**Comment by vdemeester** [comment]
@vincent-pli @nikhil-thomas I am guessing we should have a nightly build then (at first)

**Comment by nikhil-thomas** [comment]
sounds good :+1:

**Comment by houshengbo** [comment]
Do we build with operator-sdk or with the ko command as other tekton projects?
I can work on https://github.com/tektoncd/operator/issues/11 to make sure we support ko.

**Comment by anxinyf** [comment]
I cannot build operator image using build/Dockerfile via **docker build**  :
`build/_output/bin/operator: no such file or directory`

Does anyone else have such a problem?

**Comment by nikhil-thomas** [comment]
@anxinyf 
are you using the command:
```
operator-sdk build <name>:<tag>
```

**Comment by vincent-pli** [comment]
@vdemeester 
How to create a nightly build, any guide?

**Comment by timmyers** [comment]
I'm willing to try and help implement this.  As I understand a new job would need to be added to the prow config here https://github.com/tektoncd/plumbing/blob/master/prow/config.yaml#L539.

**Comment by vincent-pli** [comment]
Thanks
/assign @timmyers

**Comment by eddycharly** [comment]
@timmyers need help with this ?

**Comment by timmyers** [comment]
Help is always appreciated!  After looking more through the https://github.com/tektoncd/plumbing repo, I'm not sure if this should be done as a prow build, or as part of the tekton pipelines.

I started writing a `test/publish-images.sh`, but I'm also not sure what should be used for the nightly tag, since that normally seems to be populated by `ko`.

https://gist.github.com/timmyers/0fccc968d90e1e791623ec4543e53e0f

**Comment by eddycharly** [comment]
I don’t know how Tekton pipelines are triggered, is this done outside of prow ?

I guess, for a nightly tagging with the date is a good candidate. 

One concern is the need for docker, operator sdk supports buildah, it’s a bit tricky to get it to run in a container but definitely doable.

**Comment by eddycharly** [comment]
Something along those lines, running inside `quay.io/buildah/stable`:

```bash
set -e

# install operator sdk

OPERATOR_SDK_VERSION=v0.17.0

curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu
chmod +x operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu
mv operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk

# install go

GO_VERSION=1.13.3

curl -LO https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz
tar -xvf go${GO_VERSION}.linux-amd64.tar.gz
mv go /usr/local
rm -f go${GO_VERSION}.linux-amd64.tar.gz

mkdir /go
export GOROOT=/usr/local/go
export GOPATH=/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# build

IMAGE=?

operator-sdk build ${IMAGE} --image-builder buildah

# push

buildah push ${IMAGE}
```

**Comment by javajon** [comment]
When this is ready, the readme steps for installation 

> The following steps will install Tekton Pipeline and configure it appropriately for your cluster.

would be improved by adding another step to replace REPLACE_IMAGE in operator.yaml with the official image for Operator. I'm gathering that currently, the setting for REPLACE_IMAGE must be a locally built container from this project.

---
Consider this operator installation could be done via Helm Chart so the operator container tag can be a parameter, as well as a few other contextual installation tweaks like imagePullPolicty, resource quotas, and probes. A `helm` directory could be added to this project to compliment or depreciate the `deploy` directory.

**Comment by davidkarlsen** [comment]
Isn’t this trivial to fix? It would probably help on adoption.

**Comment by 06kellyjac** [comment]
This is still important for me

**Comment by 06kellyjac** [comment]
@vdemeester correct I just looked at the `release.yaml` from the operator release in the GH Releases tab & it had an image in gcr and I was able to pull it:

`gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/manager:v0.15.1-1@sha256:825f32940cbb327728b412dcab480210b72150bcdc45a6345f5d6a8f7d7d1eed`

/close

**Comment by vdemeester** [comment]
@06kellyjac yeah, the image is published, so I think we can close indeed
/close

**Comment by 06kellyjac** [comment]
Thanks everyone. This removes one of the extra steps that gets in the way of playing with the operator. Much appreciated.
