### ISSUE TITLE
Feature Request:  Add "Tekton Results API" Addon

### ISSUE THREAD

**Issue by ibotty** [tektoncd/operator#163]
It would be great to be able to deploy [Tekton Results API](https://github.com/tektoncd/experimental/tree/master/results) via TektonAddon.

Once  tektoncd/experimental#652 is fixed, it should only need definitions in `/command/manager/kodata/resources/addons/` (and documentation).  I can create a pull request adding it, if desired.

**Comment by vdemeester** [comment]
@ibotty Thanks for the issue. We are waiting for the results API project to be "moved" to [`tektoncd/results`](https://github.com/tektoncd/results)

/kind feature
