### ISSUE TITLE
Allow for Pod Security Admission Modifications to Tekton Pipelines

### ISSUE THREAD

**Issue by blakeromano** [tektoncd/operator#1655]
### Feature request

When the Tekton Operator generates the Tekton Pipelines namespace, there should be configuration to allow updating the Pod Security Admission label.

### Use case

For prototyping environments or other environments where there is a less strict requirement for pipelines to have pods with heightened privledges it allows for faster development which the Tekton Operator overwrites if manually changed.

**Comment by vdemeester** [comment]
Hey @blakeromano,

I am not sure if I am understanding the use-case too much. Is it to run pipelines/tasks in the `tekton-pipelines` namesace or something else ? (like developing `tektoncd/pipeline` or some components ?

**Comment by blakeromano** [comment]
I guess I am not sure what best practice in terms of should you run your tasks/pipelines in the same NS as where the tekton pipelines is deployed? My assumption was always yes you should.

**Comment by vdemeester** [comment]
> I guess I am not sure what best practice in terms of should you run your tasks/pipelines in the same NS as where the tekton pipelines is deployed? My assumption was always yes you should.

Ah this is, in most case, an anti-pattern to run Task and Pipeline in the same namespace as tektoncd/pipeline is installed. The controller watches the full cluster by default and thus, you can run TaskRun and PipelineRun anywhere (you have the rights to). Having `tekton-pipelines` (or the namespace where it is installed) dedicated to the machinery makes it less prone to issues (like deletion of deployment, …). See `tekton-pipelines` namespace as the `kube-system` for tektoncd.
