### ISSUE TITLE
Direct update to deployment is happening

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/operator#1663]
# Issue:

Direct update to Deployment is happening with v0.67.x Operator though the deployments were created by Installersets
ex:
```
kubectl edit deployment tekton-triggers-controller
```
added env in spec
```
env:
- name: hi
  value: hello
```
Pod recreated with this env and deployments are not overiden by TektonInstallerSets

# Expected Behavior

Direct update to deployment should not be allowed

# Actual Behavior
Direct update to deployment happening

# Steps to Reproduce the Problem

1. Install v0.67.x 
2. edit any deployment ex: `kubectl edit deployment tekton-triggers-controller`
3. then you see values are exist

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **0.47.x**

- Tekton Operator version:

  **0.67.x**

**Comment by savitaashture** [comment]
Its a regression issue in 0.67.x

do we need to have a release for this ?
cc @vdemeester

**Comment by vdemeester** [comment]
@savitaashture yes we probably need a release for this.
