### ISSUE TITLE
Create a directory named vendor for all the dependencies

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/operator#17]
We need to have a script, e.g. ./hack/update-deps.sh to update/generate the dependecies and save them under vendor directory.

This is a good step for code compiling on local machines after imported into IDEs.

**Comment by houshengbo** [comment]
As I mentioned in the comment: https://github.com/tektoncd/operator/pull/23#issuecomment-521335139, operator-sdk command cannot find the dependencies under the folder vendor/.

I verified it locally with the version 0.9.0 of operator-sdk, it did not find the modules under vendor, when I set `GOFLAGS=-mod=vendor`.

**Comment by houshengbo** [comment]
OK, the vendor generated under mac does not work under ubuntu.

**Comment by houshengbo** [comment]
It is something wrong with the file vendor/modules.txt.

This is what I have tested: I backup the vendor as vendor_backup in prow job, and used the prow job to generate the new vendor. I only copy the file vendor/modules.txt generated by the prow job and cp it to the vendor_backup folder. Remove the vendor folder and revert vendor_backup to vendor. After all the above steps are done, the openrator-sdk build command succeeded.

What could be the issue with vendor/modules.txt generated locally on mac?

**Comment by sthaha** [comment]
> This is a good step for code compiling on local machines after imported into IDEs.

@houshengbo with `go mod` wouldn't the packages get caches under `$GOPATH/pkg/mod` the first time you build and will be reused, i.e. wouldn't download it again which makes the need for storing every dependency under `vendor` unnecessary?

**Comment by houshengbo** [comment]
@sthaha It is downloaded under $GOPATH/pkg/mod, but it is not imported in some IDEs.
Once they are put under the dir vendor, they get automatically imported.
