### ISSUE TITLE
update version to include newer tekton pipelines releases and publish current version on operatorhub

### ISSUE THREAD

**Issue by ibotty** [tektoncd/operator#173]
### Feature request
It would be great to have newer tekton versions.

**Comment by nikhil-thomas** [comment]
we are focusing on our efforts to rewrite this operator using knative/pkg as the controller runtime instead of operator-sdk: https://github.com/tektoncd/operator/tree/main. 

The work will be complete in maximum 2 weeks, then we shall constantly make releases with pipelines and triggers releases.
ref: https://github.com/tektoncd/operator/pulls?q=is%3Apr+base%3Amain+is%3Aclosed+is%3Amerged

**Comment by aelbarkani** [comment]
Any update on this topic ? I'm itching to test the new version xD

**Comment by aelbarkani** [comment]
We had to abandon Tekton as a potential engine for CI/CD on OKD unfortunately. We couln't test easily any new version since no new releases of the operator have been published since Aug 2020...

**Comment by nikhil-thomas** [comment]
hi, we had to make a major refactoring of this operator. We moved the code from a operator-sdk based implementation to a knative/pkg base implementation. All the other components of Tekton (Pipelines, Triggers...) etc are written using knative/pkg controller runtime. At present, each component has its own CRD and reconcile loop In addition, we have also added support for platform based operator code management in the codebase.

We will be making new releases withing a month.

Ref:
- operator-sdk based implementation: https://github.com/tektoncd/operator/tree/master
- current knative/pkg based implementation: https://github.com/tektoncd/operator

**Comment by vdemeester** [comment]
> We will be making new releases withing a month.

And monthly from now on.

> We had to abandon Tekton as a potential engine for CI/CD on OKD unfortunately. We couln't test easily any new version since no new releases of the operator have been published since Aug 2020...

The operator is not the only way to try and install Tekton. It should be the preferred way once we are on a "normal"/"stable" release cadence, but it's definitely possible to install tekton through tektoncd/pipeline, … release files.

**Comment by aelbarkani** [comment]
> The operator is not the only way to try and install Tekton. It should be the preferred way once we are on a "normal"/"stable" release cadence, but it's definitely possible to install tekton through tektoncd/pipeline, … release files.

That's true @vdemeester, but we were interested in having Tekton integrated into OpenShift console, and the operator seems the only way to have it. Or is there another way to get it ?

**Comment by vdemeester** [comment]
> That's true @vdemeester, but we were interested in having Tekton integrated into OpenShift console, and the operator seems the only way to have it. Or is there another way to get it ?

@aelbarkani depends of what you mean by "integrated into OpenShift console". As far as I know, the console react to the tekton api being present so even if you don't install it through the operator hub from the console, you would see the UI pieces showed there (there might be some issues though as it might not be tested against nor supported depending on the version you deploy, but…). 

Also, quick update, next week, a release should happen (providing `release.yaml` appliable on k8s and openshift) and we'll look into how quickly we can have it publish in the community side of operator hub.

**Comment by aelbarkani** [comment]
Thanks for these updates ! It's ok to have a release.yaml that points to a specific version, no need for operator hub indeed. What I meant is that installation through operator is necessary for OpenShift console, whether with release.yaml or operator hub. The regular installation with tektoncd/pipeline doesn't offer these capabilities, since I think the code for that feature is hosted here in this repo and not tektoncd/pipeline.

**Comment by nikhil-thomas** [comment]
`v0.21.0-1` release.yaml: https://github.com/tektoncd/operator/releases/tag/v0.21.0-1

operatorhub.io coming up

**Comment by aelbarkani** [comment]
awesome !

**Comment by aelbarkani** [comment]
@nikhil-thomas unfortunately I cannot make this work with openshift. It seems this file is only for Kubernetes...

**Comment by ibotty** [comment]
> operatorhub.io coming up

Is there an ETA?

**Comment by aelbarkani** [comment]
@nikhil-thomas just FYI, we are not able to install the operator through ArgoCD in OKD seamlessly, this file https://storage.googleapis.com/tekton-releases/operator/previous/v0.22.0-1/release.yaml is only for Kubernetes. And OperatorHub publishing seems not published yet. maybe we are missing something ?

**Comment by nikhil-thomas** [comment]
we have an update:
 ✅  `v0.23.0-2` released on operaotrhub.io
 
 we were working on making the process of publishing to operatorhub simpler from our side. From now on, there will regular versioned updates to operatorHub.

**Comment by aelbarkani** [comment]
Hi @nikhil-thomas. Unfortunately that broke our current installation in OKD. The deployed version is Kubernetes, not Openshift's/OKD. We get this error: 
`Error: container create failed: time="2021-05-31T14:20:04Z" level=error msg="container_linux.go:367: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied" `

Is there a way we can easily Openshift's/OKD flavor ?

**Comment by nikhil-thomas** [comment]
cc @vdemeester

**Comment by vdemeester** [comment]
@aelbarkani on which pod/container do you get this error ? (controller, webhook, task's pod, … ?)
But yeah, indeed, I think we should aim to publish tektoncd/operator kubernetes flavor on operatorhub kubernetes versino, and the openshift flavor for openshift community (aka okd).

**Comment by aelbarkani** [comment]
in task pods and another pod that pops up called affinity or something like that. in order to solve this we had to uninstall the operator and to build the images from source by using Makefile, which of course is not compatible with Gitops way of managing our deployments

**Comment by vdemeester** [comment]
@aelbarkani ok so you are hitting this bug then: https://github.com/tektoncd/pipeline/issues/3968#issuecomment-848470770

**Comment by aelbarkani** [comment]
@vdemeester yes, we get the same error in both affinity-assistant and the task pod. solved by installing openshift flavor with "make apply"

**Comment by vdemeester** [comment]
As @nikhil-thomas said in the comment linked

> tektoncd/operator, creates additional ClusterRole and Rolebinding, https://github.com/tektoncd/operator/blob/main/cmd/openshift/operator/kodata/tekton-pipeline/0.22.0/01-clusterrole.yaml.

we (openshift-pipelines team) need to discuss how to publish the openshit target (and more often) for OKD.

**Comment by aelbarkani** [comment]
sorry for being so pushy @vdemeester @nikhil-thomas, but any chance to get soon a newer version of the operator for OKD :) ?

**Comment by nikhil-thomas** [comment]
https://github.com/tektoncd/operator/tree/main/docs/release#tektoncd-operator-release

As mentioned here 👆we will be releasing tektoncd/operator every two weeks.
I think this must be a good enough resolution for this issue.

**Comment by ibotty** [comment]
But the version on operatorhub is still 0.49.0 and not the recent (at the time of writing) 0.54.0.  The file mentioning the plan is much older than the last release so I think it's not handled that way yet.
