### ISSUE TITLE
Remove from TektonResult properties fields not required - s3 and DB (Results)

### ISSUE THREAD

**Issue by khrm** [tektoncd/operator#1746]
# Expected Behavior
TektonResult CR shouldn't have properties related to DB and s3 after this pr https://github.com/tektoncd/operator/pull/1547.
# Actual Behavior
We still have DB and S3-related properties. DB properties aren't used and the user can mistakenly expose these credentials.

**Comment by khrm** [comment]
@jkandasa

**Comment by jkandasa** [comment]
I think this is addressed in #1747
Please reopen if it is not.
