### ISSUE TITLE
add "priorityClassName" under options in deployment and statefulset

### ISSUE THREAD

**Issue by jkandasa** [tektoncd/operator#1835]
### Feature request

`priorityClassName` is a request from #1824, currently not allowed to update `priorityClassName` via `options` to deployment and StatefulSet.

implement `priorityClassName` under deployment and statefulset in `options`

### Use case
#1824

**Comment by jkandasa** [comment]
@pratap0007 thanks to working on this issue.
hints:
* https://github.com/tektoncd/operator/blob/572eec2fd2093bc3afa505ce5f887d22e76785ab/pkg/reconciler/common/transformer_additional_options.go#L254-L266
* https://github.com/tektoncd/operator/blob/572eec2fd2093bc3afa505ce5f887d22e76785ab/pkg/reconciler/common/transformer_additional_options.go#L434-L457

**Comment by pratap0007** [comment]
@jkandasa thank  you for giving hints, will start to work on it
