### ISSUE TITLE
Provide ability to add additional environment variables, volumes and volumeMounts to Chains Controller

### ISSUE THREAD

**Issue by sabre1041** [tektoncd/operator#1912]
### Feature request

Provide the ability to customize aspects of the Tekton Chains controller. In particular:L

* Environment Variables
* Volume/VolumeMounts

### Use case

[SPIFFE](https://spiffe.io) is one of the supported methods by Sigstore for providing identities to workloads. As the Tekton Chains controller represents a workload that manages signing content, the _Deployment_ needs to be augmented with the tooling to integrate SPIFFE. In this case, it requires additional volume/volumeMounts and environment variables to be added to the Tekton Chains Controller. 

Since other aspects of Tekton are customizable from within the `TektonConfig` resource, such as _pipelines_, similar capability/functionality should be provided for Tekton Chains as well.

**Comment by jkandasa** [comment]
@sabre1041 we have a field called `options`. it is available for all the components.
Can you please have a look on https://tekton.dev/docs/operator/tektonconfig/#additional-fields-as-options ?
I hope `options` can satisfy your request.

**Comment by sabre1041** [comment]
@jkandasa `options` worked like a charm! Thanks for pointing it out!
