### ISSUE TITLE
Tekton Operator webhook missing `WEBHOOK_POD_NAME` environment variable

### ISSUE THREAD

**Issue by A1994SC** [tektoncd/operator#1917]
# Expected Behavior

The `WEBHOOK_POD_NAME` environment variable to be populated.

# Actual Behavior

The `WEBHOOK_POD_NAME` environment variable is not populated.

# Steps to Reproduce the Problem

1. `helm repo add tekton-operator https://raw.githubusercontent.com/tektoncd/operator/gh-pages`
2. `helm repo update`
3. `helm -n tekton-operator  install tekton-operator/tekton-operator --create-namespace --version 0.69.1`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```shell
kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```shell
tkn version
Client version: 0.32.2
Pipeline version: v0.53.3
```

- Pod logs

```shell
kubectl -n tekton-operator logs tekton-operator-webhook-6c99c9f54f-bz4m2 
{"level":"info","ts":1704241734.3142097,"logger":"fallback.manifestival","caller":"manifestival@v0.7.2/manifestival.go:71","msg":"Parsing manifest"}
{"level":"fatal","ts":1704241734.35777,"logger":"fallback","caller":"webhook/webhook_init.go:82","msg":"error creating webhook installerset","error":"pod name environment variable[WEBHOOK_POD_NAME] details are not set","stacktrace":"github.com/tektoncd/operator/pkg/webhook.CreateWebhookResources\n\tgithub.com/tektoncd/operator/pkg/webhook/webhook_init.go:82\nmain.main\n\tgithub.com/tektoncd/operator/cmd/kubernetes/webhook/main.go:62\nruntime.main\n\truntime/proc.go:250"}

```

**Comment by piyush-garg** [comment]
cc @jkandasa
