### ISSUE TITLE
missing plain crd's

### ISSUE THREAD

**Issue by wibed** [tektoncd/operator#1927]
i would like to install the crd's for the whole stack without having to reference 5 implementation of the same structure.

is there a crd bundle, ideally with a kustomization.yaml located i can reference to install crd's independent from any predetermined structure i have to pretend to follow?

**Comment by jkandasa** [comment]
@wibed can you please elaborate your question? we have `release.yaml` on each release, which has all the CRDs in one location. In addition to that, in development environment, you can use `make apply` or `make apply-cr` to update the CRDs. Thanks!

**Comment by vdemeester** [comment]
@wibed given there has been no answer for a while, I'll close. Feel free to reach out for me to re-open if need be.

**Comment by kastl-ars** [comment]
As just stated in https://github.com/tektoncd/pipeline/issues/7550:

I would like to chime in on that. Having the CRDs and the "normal" resources in the same YAML file makes applying this via e.g. ArgoCD tricky.

From what I gathered so far: As CRDs tend to be really large, the usual "last-applied" annotation causes issues, as it normally contains the whole content of the object. But does not allow storing a whole CRD in there.

So those CRDs are always being shown as out of sync.

So splitting out the CRDs into a separate file would be really helpful. (Charts would be even nicer...)
