### ISSUE TITLE
On install, conflicting components are created

### ISSUE THREAD

**Issue by corinz** [tektoncd/operator#2097]
When installing the crds, and operator via release.yaml with the instructions found [here](https://tekton.dev/docs/operator/install/), the operator launches some Tekton components.

After step 1 is completed, the instructions advise the creation of a TektonConfig, which, after applied, deletes the original components, and replaces with them with new components (pods).

If the intent is to use release.yaml with a TektonConfig, the release.yaml should not create any components by default.

I propose that release.yaml only create the CRDs and operator, without installing any components by default. 

Proposal: change `AUTOINSTALL_COMPONENTS` env var set in the `tekton-operator/tekton-config-defaults` configmap be set to `false` by default to prevent this collision/conflict.

**Comment by divyansh42** [comment]
As per the Slack conversation, we will be doing the documentation update to reflect the current behavior.
We are not making any changes in the present behavior as it might break/confuse the existing user's flow.

**Comment by divyansh42** [comment]
Hi @corinz 
I am trying to reproduce the issue but I don't see pods getting re-created after applying the config. Could you check again?
I just did the 2 steps mentioned [here](https://tekton.dev/docs/operator/install/)

**Comment by divyansh42** [comment]
However, I agree with your point that the first step also installs the Tekton components
