### ISSUE TITLE
Use the existing test framework for integration tests

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/operator#22]
As I mentioned on PR #21, I suggest we setup the same test framework as we use in pipeline, e.g. create a file like https://github.com/tektoncd/pipeline/blob/master/test/init_test.go#L47 to initialize the tests.

Then we are able to run the integration test with `go_test_e2e -timeout=20m ./test || failed=1`, as in https://github.com/tektoncd/pipeline/blob/master/test/e2e-tests.sh#L34.

**Comment by nikhil-thomas** [comment]
> Then we are able to run the integration test with go_test_e2e -timeout=20m ./test || failed=1, as in https://github.com/tektoncd/pipeline/blob/master/test/e2e-tests.sh#L34.

what is the advantage in doing so?

why can't we run tests using `operator-sdk test` command?
