### ISSUE TITLE
Signing key management

### ISSUE THREAD

**Issue by jkhelil** [tektoncd/operator#2295]
### Feature request
Currently, Chains lacks robust key management features, which poses potential security risks. Chains controller does not verify the validity or revocation status of signing keys, also the controller starts without ensuring the presence and validity of the required keys. 
- Chains controller should perform a startup check for the presence of required signing keys.
- Chains controller should Implement a validity check for the signing key  at startup and eventually periodically during operation (not sure if the key is loaded once or on each operation)
- The controller should panic and fail to start if no valid signing key is present.

**Comment by vdemeester** [comment]
@jkhelil aren't all of thoses (except maybe the last item) about `tektoncd/chains` only ? (and if that's the case, it should be an issue or there should be an issue on `tektoncd/chains`).

**Comment by jkhelil** [comment]
thank you @vdemeester , I was mistaken with the wrong tab
closing this and opening it on chains repo
