### ISSUE TITLE
Container Image ReNaming

### ISSUE THREAD

**Issue by ArthurVardevanyan** [tektoncd/operator#2433]
Example Images from  v0.74.0 

The Image Repositories are being appended with extra numbers

Examples, but not limited too:
- ghcr.io/tektoncd/dashboard/dashboard-9623576a202fe86c8b7d1bc489905f86
- ghcr.io/tektoncd/chains/controller-92006fd957c0afd31de6a40b3e33b39f
-ghcr.io/tektoncd/pipeline/events-a9042f7efb0cbade2a868a1ee5ddd52c:
- ghcr.io/tektoncd/pipeline/controller-10a3e32792f33651396d02b6855a6e36

Is this going to be consistent going forward, or are the repos going to change with each release going forward? 

The Image Repo Changing consistently would make it difficult to do automated image mirroring.

**Comment by vdemeester** [comment]
Hello. This is due to https://github.com/tektoncd/plumbing/issues/2157#issuecomment-2337913429, so for some component it might change still as they will move to ghcr. Note that all the images to mirror are listed in the related image of the clusterserviceversion object in the repository.
