### ISSUE TITLE
Extend extensions' capability to create resources in the cluster

### ISSUE THREAD

**Issue by concaf** [tektoncd/operator#254]
Right now the `PreReconcile`, `Reconcile` and `PostReconcile` methods in the operator's extensions not have access to the `(r *Reconciler)` and even the access to `mf.Manifest` is tedious to implement - both of these make it difficult to add resouces to the cluster via kodata or adding them programatically.

We need to fix this by either extending the `Extension` interface or some other way.

@vdemeester made an attempt to do this at https://github.com/tektoncd/operator/pull/190/files#diff-7fbb40c9518cac5a6bbd14b188493048990e2cc3eff687875b6ab2b80b14efe1R28

**Comment by nikhil-thomas** [comment]
one way to handle this is this example https://github.com/tektoncd/operator/blob/6b4b0a872d36eaadb0e02d0a542fdfc303cab586/pkg/reconciler/openshift/tektonconfig/extension.go#L173

**Comment by nikhil-thomas** [comment]
one instance where we can do something like this is the creation of targetNamespace.
https://github.com/tektoncd/operator/pull/246#discussion_r592941026

**Comment by nikhil-thomas** [comment]
still relevant
/remove-lifecycle stale
