### ISSUE TITLE
Inappropriate configuration of ImagePullPolicy with kind

### ISSUE THREAD

**Issue by rudeigerc** [tektoncd/operator#258]
# Expected Behavior

Using the local image.

# Actual Behavior

Back-off pulling image since the `ImagePullPolicy` is set as `Always`.

# Steps to Reproduce the Problem

```shell
$ KO_DOCKER_REPO=kind.local make apply

tekton-operator      pod/tekton-operator-78679499d5-9kss7             0/1     ImagePullBackOff   0          76s
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:23:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  Client version: 0.16.0
  Pipeline version: v0.21.0
  Triggers version: v0.11.2
  ```

A probable solution could be adding a new target as **kind** and patching the `ImagePullPolicy` with `IfNotPresent` when building kustomization.

**Comment by vdemeester** [comment]
/remove-lifecycle stale
@tektoncd/operator-maintainers any reason we use `Always` pull policy ?

**Comment by nikhil-thomas** [comment]
no specific reason. This got in as a default. :stuck_out_tongue:  
let us use this issue to drive efforts to make sure that operator can be deployed on kind.
