### ISSUE TITLE
TektonConfig instance autocreate for all platforms by default

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/operator#267]
### Feature request

Auto create an instance of TektonConfig when the operator is installed

- a flag could be provided (command line flag, feature gate confifMap ...) to disable this feature.

### Use case

At present, a user has to install an operator release and then manually create an instance of TektonConfig to install components like TektonPipeline, TektonTriggers, TektonDashboard...

**Comment by vince-franco** [comment]
Love this idea!
