### ISSUE TITLE
Cannot designate PR to build nightly image

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/operator#29]
# Expected Behavior
We should build the the nightly image based on an existing commit in master. We should remove this line: https://github.com/tektoncd/operator/blob/master/test/presubmit-tests.sh#L57.

# Actual Behavior
We build the the nightly image on every pending PR.

# Steps to Reproduce the Problem

1. Open a PR
2. The image gcr.io/tekton-nightly/tektoncd-operator is built with https://github.com/tektoncd/operator/blob/master/test/presubmit-tests.sh#L57.

# Additional Info

**Comment by vdemeester** [comment]
@houshengbo the nightly would be on postsubmit (aka merge on master), so this line in `presubmit-tests.sh` would still be needed as it builds the image from the PR changes (if any).

But having a nightly image would be more than nice :angel:

**Comment by houshengbo** [comment]
@vdemeester @nikhil-thomas @sthaha 
When we run the command along operator-sdk build gcr.io/tekton-nightly/tektoncd-operator, do we push the image into gcr.io/tekton-nightly or not? (I thought we did?)

**Comment by vincent-pli** [comment]
No, need push manually.
