### ISSUE TITLE
0.22.0-2 yaml from the release is missing

### ISSUE THREAD

**Issue by 06kellyjac** [tektoncd/operator#296]
https://github.com/tektoncd/operator/releases/tag/v0.22.0-2

https://storage.googleapis.com/tekton-releases/operator/previous/v0.22.0-2/release.yaml

```xml
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Details>
    No such object: tekton-releases/operator/previous/v0.22.0-2/release.yaml
  </Details>
</Error>
```

does `/previous` only work for older releases? Should the path be different for latest releases?

**Comment by vdemeester** [comment]
@06kellyjac should be fixed now. There has been a *glitch* in the release, fixed it manually 😉

**Comment by 06kellyjac** [comment]
Worked. Thanks @vdemeester
