### ISSUE TITLE
Publish Operator on OperatorHub.io

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/operator#3]
One we will have our first release, we're gonna want to publish the upstream operator on operatorhub.io. This issue is to track that.

**Comment by sbose78** [comment]
I'll need this for the upstream Build v2 operator dependency resolution :)

**Comment by ibotty** [comment]
Can this ticket be reopened?  It would still be great to have the operator on operatorhub.

**Comment by sbose78** [comment]
Is there an ETA on the Kubernetes operator @nikhil-thomas  :) ?

**Comment by sbose78** [comment]
This is done https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/tektoncd-operator and can be closed?

**Comment by vdemeester** [comment]
I think so yes :upside_down_face: 
/close
