### ISSUE TITLE
Multiple Event Listener Service in same namespace is not working properly on OpenShift

### ISSUE THREAD

**Issue by AdlerFleurant** [tektoncd/operator#304]
# Expected Behavior

It should be possible to create multiple working event listener on a single namespace in OpenShift.

# Actual Behavior

While multiple event listener is created. It will create multiple kubernetes service, however it will annotate all of them with the same: service.beta.openshift.io/serving-cert-secret-name=tls-secret-key. The result is that the generated secret will only have certificates for one of the service and the other one will fail with an error similar to:
```
2021/05/09 19:17:18 http: TLS handshake error from 10.128.2.13:56342: local error: tls: bad record MAC
```

# Steps to Reproduce the Problem

1. Create one EventListener
2. Create a Second EventListener
3. Trigger the second one, it will fail with an error similar to: `2021/05/09 19:17:18 http: TLS handshake error from 10.128.2.13:56342: local error: tls: bad record MAC` on the eventlistener pod.

# Additional Info

This error is due to hard-coded "tls-secret-key" on https://github.com/tektoncd/operator/blob/main/pkg/reconciler/openshift/annotation/annotation.go. The name of the secret key should be the same as the service name as recommended here: https://docs.openshift.com/container-platform/4.7/security/certificates/service-serving-certificate.html

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
 Client Version: 4.7.0-0.okd-2021-03-21-094146
Server Version: 4.7.0-0.okd-2021-04-24-103438
Kubernetes Version: v1.20.0-1058+7d0a2b269a2741-dirty
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.17.2
Pipeline version: v0.22.0
Triggers version: v0.12.1
```

**Comment by AdlerFleurant** [comment]
@savitaashture , it seems that commit b5c51485bf74b71501eb28f86b5b9f314b622768 resolves this but this is still opened.

b5c51485bf74b71501eb28f86b5b9f314b622768

**Comment by savitaashture** [comment]
> @savitaashture , it seems that commit [b5c5148](https://github.com/tektoncd/operator/commit/b5c51485bf74b71501eb28f86b5b9f314b622768) resolves this but this is still open.

Yup 
Forgot to close the issue :)
