### ISSUE TITLE
Change the git-in it container

### ISSUE THREAD

**Issue by mjschmidt** [tektoncd/operator#318]
# Expected Behavior
I would expect the insecure-skip-tls-verify pipeline resource set to false (I also tried true) to cause my git pipeline resource to pull my privately hosted gitlab repo despite it having a self signed certificate. 

# Actual Behavior
The skip-tls-verify is not working as expected
Ssl certificate problem: unable to get local issuer certificate\n

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info
MAIN QUESTION HERE:
Is there a way to specify using the operator your own custom git-init container in either the pipeline resource, or in the pipelines deployment itself when using the operator? 

- Kubernetes version:
1.20.5
  **Output of `kubectl version`:**

  ```
Client: 1.20.4
Server: 1.20.5
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
Client: 0.18.0
Pipeline: 0.23.0
Triggers: 0.13.0
Dash: 0.16.0

**Comment by nikhil-thomas** [comment]
in short, it is possible.

At present, we can specify image replacements to any deployment (in spec.image:, in args to entrypoint and in ENV) by specifying the replacement image as a ENV to the operator deployment. But it is not yet configurable through the operators, CRD instance spec.

so if you are not installing the operator using one of the releases on thins repository, all you have to do is to set a ENV on the operator's deployement spec (in the release.yaml [here](https://github.com/tektoncd/operator/blob/8734ca2ea98e2220127b3159b13e0521dc943ab5/config/kubernetes/operator.yaml#L26).

```
- name: IMAGE_PIPELINES_ARG__GIT_IMAGE
  value: <replacement-image>
```

this is a hole in our documentation. we shall fix it immediately.
for now you can refer: https://github.com/openshift/tektoncd-pipeline-operator#override-images

**Comment by vdemeester** [comment]
@mjschmidt can you share you yamls (pipeline, tasks, runs, pipelineresource, …). If you are using PipelineResources, and the git PipelineResource in particulare, there is a defined set of params you can pass (documented [here](https://github.com/tektoncd/pipeline/blob/main/docs/resources.md#git-resource)). For example if you use the following `PipelineResource` definition, the `insecure-skip-tls-verify` value is not taking into account by anything.

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: wizzbang-git
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/wizzbangcorp/wizzbang.git
    - name: revision
      value: master
    - name: insecure-skip-tls-verify
      value: false
```

Instead, as [documented](https://github.com/tektoncd/pipeline/blob/main/docs/resources.md#git-resource) you should use `sslVerify`. In PipelineResource, any params that is not documented will be completely ignored. Also note that `PipelineResource` are deprecated and it might be worth using the `git-clone` task instead (see in the [`tektoncd/catalog`](https://github.com/tektoncd/catalog).

**Comment by mjschmidt** [comment]
@vdemeester that param wasn't working, and you have to set it as type string so it would be "false" not false. But yeah it didn't work.

**Comment by mjschmidt** [comment]
I also updated with my versions as I do believe tekton does have a bug with that param.

**Comment by mjschmidt** [comment]
And may I say further, the reason I moved to the operator was because the HPA and webhook were not working correctly. I would install and the webhook would disappear and then the HPA would go into pending saying it could not find the webhook.

How would I go about debugging that? My preference is to use the base installation.

**Comment by mjschmidt** [comment]
Also i appreciate the info so far.

**Comment by vdemeester** [comment]
> @vdemeester that param wasn't working, and you have to set it as type string so it would be "false" not false. But yeah it didn't work.

Which param ? According to the doc, the following should work

```yam
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: wizzbang-git
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/wizzbangcorp/wizzbang.git
    - name: revision
      value: master
    - name: insecure-skip-tls-verify
      value: false
```

If not, we need to open a bug report on [`tektoncd/pipeline`](https://github.com/tektoncd/pipeline)

**Comment by vdemeester** [comment]
> And may I say further, the reason I moved to the operator was because the HPA and webhook were not working correctly. I would install and the webhook would disappear and then the HPA would go into pending saying it could not find the webhook.
> 
> How would I go about debugging that? My preference is to use the base installation.
> 
> This may be a seperate bug report or help wanted?

Yep, should be a separate bug or discussion 😛

**Comment by mjschmidt** [comment]
> > @vdemeester that param wasn't working, and you have to set it as type string so it would be "false" not false. But yeah it didn't work.
> 
> Which param ? According to the doc, the following should work
> 
> ```
> apiVersion: tekton.dev/v1alpha1
> kind: PipelineResource
> metadata:
>   name: wizzbang-git
>   namespace: default
> spec:
>   type: git
>   params:
>     - name: url
>       value: https://github.com/wizzbangcorp/wizzbang.git
>     - name: revision
>       value: master
>     - name: insecure-skip-tls-verify
>       value: false
> ```
> 
> If not, we need to open a bug report on [`tektoncd/pipeline`](https://github.com/tektoncd/pipeline)

Have you tried using this param though? Because at the very least it should fail because false is not of type string. And then when the param was used it did not do anything. I still got a fail with an ssl error.

**Comment by vdemeester** [comment]
> Have you tried using this param though? Because at the very least it should fail because false is not of type string. And then when the param was used it did not do anything. I still got a fail with an ssl error.

Oh way, I messed up in my example, according to the doc, **this** should work

```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: wizzbang-git
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/wizzbangcorp/wizzbang.git
    - name: revision
      value: master
    - name: sslVerify
      value: false
```

Sorry, I wrote the wrong param name 🤦🏼‍♂️

**Comment by mjschmidt** [comment]
> > Have you tried using this param though? Because at the very least it should fail because false is not of type string. And then when the param was used it did not do anything. I still got a fail with an ssl error.
> 
> Oh way, I messed up in my example, according to the doc, **this** should work
> 
> ```yaml
> apiVersion: tekton.dev/v1alpha1
> kind: PipelineResource
> metadata:
>   name: wizzbang-git
>   namespace: default
> spec:
>   type: git
>   params:
>     - name: url
>       value: https://github.com/wizzbangcorp/wizzbang.git
>     - name: revision
>       value: master
>     - name: sslVerify
>       value: false
> ```
> 
> Sorry, I wrote the wrong param name 🤦🏼‍♂️

I'll try it on Monday thank you.

**Comment by mjschmidt** [comment]
Leaving this ticket open because the need for being able to set the git init container that should be used still needs to be configurable. However the sslVerify does in fact work if set to false as a string. So that's a good work around I'm the meantime.
