### ISSUE TITLE
Feature Request: Add Tekton Chains addon

### ISSUE THREAD

**Issue by imjasonh** [tektoncd/operator#319]
### Feature request

[Tekton Chains](https://github.com/tektoncd/chains) runs a separate controller that watches Tekton executions and records/signs details of execution history to better ensure supply chain integrity.

It'd be great if users could instruct the operator to install and configure the chains controller.

### Use case

I'm a (human) operator who's sensitive to security, and wants to track and sign provenance information for artifacts built by Tekton Pipelines. Chains looks great, but installing it and upgrading it myself can be a pain, and I'd prefer a (computer) operator to do that for me.

cc @dlorenc

**Comment by imjasonh** [comment]
@priyawadhwa FYI

It could be useful even just to sketch out what would config be needed for the operator to install and setup Chains. What inputs to the Operator would be needed to [setup Chains](https://github.com/tektoncd/chains#setup), and how many of those steps can be automated?

**Comment by vdemeester** [comment]
@concaf or we may create issue for each of those, if we can split into smaller parts.. and mark this one as done as it is done (it is there, but there is possible enhancements)

**Comment by jkandasa** [comment]
@concaf Is this issue still valid?

**Comment by vdemeester** [comment]
I think it can be closed.
