### ISSUE TITLE
Discussion: pick up CRD name more make sense than "Config"

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/operator#33]
When I install `Tekton/operator` on my private k8s cluster product, I feel a little uncomfortable, since a `cluster scope` and named `Config` stuff make people confuse, they think the resource is a globe configuration for the whole k8s cluster.

So, I think could we change the name, I checked `Knative/serving-operator`, they named it `KnativeServing` , so could we chose `Tekton` or `TektonPipeline`?

**Comment by vincent-pli** [comment]
@vdemeester @nikhil-thomas @sthaha 
What do you think?

**Comment by sthaha** [comment]
The reason for naming it as kind `Config` and to mandate the name `cluster` is imply that it is the **cluster wide configuration** for the operator.  It is indeed the global configuration for the `Tekton` in that cluster and would be be case until Tekton supports multi-tenancy.

e.g. what that is the global / clusterwide configuration on tekton operator 
` kubectl get config.operator.tekton.dev` -> `cluster`

show the `cluster` wide configuration
` kubectl get config.operator.tekton.dev cluster`

For the reasons above, I  am not too inclined to change it, unless there is a  good reason. 
Foo does it like Bar isn't a good reason imho.

**Comment by vincent-pli** [comment]
Thanks @sthaha 
Actually people use:
`kubectl get Config` not the verbose style upper.
So the `Config` and `cluster` seems too much general.
`kubectl get TektonPipeline` is better I think.

**Comment by k** [comment]
This also makes me nervous, I personally wouldn't use this for that reason alone, or perhaps build my own fork with everything renamed.

**Comment by sthaha** [comment]
> I have yet to see an operator that would use an overloaded name like Config or Cluster or even Addon for the Kind: of a CRD. I believe Addon should be changed to TektonAddon as well.

For the recored, I am open to a name change :-) but I beg to differ with the argument above. If we extrapolate that logic, A `Task` which is an equally overloaded term should be named a `TektonTask` and `Pipeline` a `TektonPipeline and a `ClusterTask` a `TektonClusterTask` 

But I think `G`VK of the k8s api is precisely meant for this specific purpose ( avoid name conflicts) . The `Task` is in the `tekton.dev` group and that allows for `foobar.baz/Task`

**Comment by sthaha** [comment]
@vincent-pli 

> Actually people use:
> kubectl get Config not the verbose style upper.
> So the Config and cluster seems too much general.
> kubectl get TektonPipeline is better I think.

Sorry, I missed this comment :( ... I agree that is a good reason to change 🤗 
How about: `kubeclt get TektonConfig` ?

**Comment by vincent-pli** [comment]
@sthaha @nikhil-thomas 
What about `TektonPipeline` and `TektonAddons`? I'm afraid `TektonConfig` will be misunderstand as configuration for `Tekton`.

**Comment by k** [comment]
> For the record, I am open to a name change :-) but I beg to differ with the argument above. If we extrapolate that logic, A `Task` which is an equally overloaded term should be named a `TektonTask` and `Pipeline` a `TektonPipeline` and `ClusterTask` a `TektonClusterTask`

I see your point! For some reason `Config` and `ClusterConfig` seem like a more heavily overloaded term at the cluster level, it seems like we are configuring the cluster itself, like kubeadm or the [Cluster API](https://cluster-api.sigs.k8s.io/) or something. It also might be because these Operator CRDs are not interacted with enough to warrant such as concise name, whereas Tekton pipeline deployments and Tekton addons are more sparsely used and don't need to be very nicely readable and typable as often as Tasks and Pipelines...

**Comment by nikhil-thomas** [comment]
@vincent-pli @k 
I agree with your comments. :+1: 
The enduser experience will definitely be better with explict Kind names. `TektonPIpeline` and `TektonAddons` are good. How about `TektoncdCore` and `TektoncdAddons`? 

We are in the process of setting up a **Tektoncd/Operator Weekly 30 min Work Group Meeting**.
Please record your time slot preference in this poll: https://docs.google.com/forms/d/e/1FAIpQLSe9sR8eyshh-QrWythLgYWz7XTlZPRLQRki_Y4pRv0ewpCftQ/viewform?usp=sf_link

Lets make a final call on this in our first meeting. :)

cc @sthaha @vdemeester @houshengbo

**Comment by houshengbo** [comment]
Based on our discussion in the meeting, we will change the names into Change to TektonPipeline and TektonAddon.
