### ISSUE TITLE
The issue of `deployOperator` in the test case with operator-sdk

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/operator#34]
I found an issue with the operator-sdk we are using for tekton operator, when I am working on the PR https://github.com/tektoncd/operator/pull/24.

The reconcile function can be kicked-off every time there is change with CD or deployment, if we launch the operator locally, with the function `deployOperator` in the test case at https://github.com/tektoncd/operator/blob/master/test/testgroups/cluster_crd.go#L26.

If we check the status of the deployment and revive the pipeline deployment, it is possible that reconcile function needs to be kicked-off multiple times to reach the expected status. (CR created, kicking off reconcile; deployment 1 created, kicking off reconcile; deployment 2 created, kicking off reconcile; deployment 1 deleted, kicking off reconcile; deployment 2 deleted, kicking off reconcile...)

However, with the operator launched LOCALLY with the function `deployOperator` in the test case, reconcile func sometimes MISSES the call. If we build an image, and run the operator with the kubectl apply command, this issue does not apply.

**Comment by houshengbo** [comment]
@sthaha @nikhil-thomas PLZ pay attention to this.

**Comment by nikhil-thomas** [comment]
could you check the value of `WATCH_NAMESPACE` env during test. It should be "". 
`WATCH_NAMESPACE=""` means the controller will watch all namespaces for changes.

> If we build an image, and run the operator with the kubectl apply command, this issue does not apply.
as we are setting the the environment variable in the deployment manifest
https://github.com/tektoncd/operator/blob/588e1d0ff3f16b1454c378aaed8767312caf3598/deploy/operator.yaml#L24

**Comment by Dileep1314** [comment]
TR

**Comment by Dileep1314** [comment]
TR
