### ISSUE TITLE
AffinityAssistant configuration on OpenShift not taken into account

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/operator#372]
# Expected Behavior

Changing the TektonPipeline configuration `disable-affinity-assistant` to `false` is taken into account under OpenShift and the affinity assistant is enabled.

# Actual Behavior

Changing the TektonPipeline configuration `disable-affinity-assistant` to `false` is not taken into account, it is forced to `true` by the controller (see [here](https://github.com/tektoncd/operator/blob/main/pkg/reconciler/openshift/tektonpipeline/extension.go#L141))

# Steps to Reproduce the Problem

1. Install the operator
2. Update the `TektonPipeline` CR
3. Look at the `openshift/pipelines` `feature-flags` configmap.

/cc @nikhil-thomas @sm43 to correct me if I am saying something wrong

**Comment by sm43** [comment]
yep you are correct.
webhook by default will enable `affinity-assistant`
for OpenShift, we disable it in extension
in case of OpenShift while reconciling we don't know if it was disabled by webhook (as it set false as default value if not set) or user
so we need to find a way where we know that it was changed by user to false and not webhook 😄

**Comment by vdemeester** [comment]
@sm43 indeed 👼🏼 
I think we shouldn't default the options in CR ; that way we know if the user explicitly did set them and thus we can override the `tektoncd/pipeline` configuration based on that, on any platform.
