### ISSUE TITLE
Read-only option for Dashboard

### ISSUE THREAD

**Issue by MarcusNoble** [tektoncd/operator#399]
### Feature request

Provide a parameter to install the dashboard in a read-only state.

### Use case

We offer the dashboard as viewable by everyone in the company but don't want them to be able to perform any changes or trigger any pipelines.

**Comment by nikhil-thomas** [comment]
@MarcusNoble Thank you for expressing interest in taking this up (in the slack thread) :slightly_smiling_face: :+1: 

Let me add some details to get you started. :technologist: 

First we have to bring in the `readonly` dashboard release.yaml in addition to release.yaml fetched currently, by editing [this](https://github.com/tektoncd/operator/blob/dcf6156122cd8389673623640b3433d94b83d208/hack/fetch-releases.sh#L86).

Next, we have to provide a mechanism to let operator controlelr know whether to read only dashboard, either by adding a  spec field in TektonDashboard CRD  [here](https://github.com/tektoncd/operator/blob/dcf6156122cd8389673623640b3433d94b83d208/pkg/apis/operator/v1alpha1/tektondashboard_types.go#L57 ). 
or  else we can add a new config to operator's config-defaults config map [here](https://github.com/tektoncd/operator/blob/main/config/base/tekton-config-defaults.yaml)

Then use the spec/configMap setting in the TetkonDashbard reconciler [here](https://github.com/tektoncd/operator/blob/main/pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go#L93)

cc @vdemeester @vinamra28
