### ISSUE TITLE
export GO111MODULE=on makes `ko apply` support extremely slow

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/operator#40]
To enable `ko apply` support to build the image, and run the operator, we have to get rid of `export GO111MODULE=on` in the scripts, since it will severely slow down the image build and operator deployment, and even make the pod fail to launch before timeout.

**Comment by nikhil-thomas** [comment]
Good find. It makes sense
ref: https://github.com/operator-framework/operator-sdk/blob/447f0b776ef1be677d6978f1094115555a5f9731/internal/util/projutil/exec.go#L121

**Comment by ImJasonH** [comment]
Is this still the case? `ko` should support Go modules fairly efficiently, if it doesn't we should investigate it as a bug in `ko`.

**Comment by houshengbo** [comment]
@ImJasonH If we set GO111MODULE=on before running kp apply command, all the dependencies will be pulled, which will surely make the process low down.
