### ISSUE TITLE
[Question] Should we make all components common for all platforms

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/operator#400]
At present some of the components are common to all target platforms. Components like TektonDashboard, TektonResults are not included in the builds for all platforms.

Questions

1. should we make all commponents common to all platforms in this tektoncd/operator repository.
2. if we do make everything common how do we disable a few components for a specific build if needed.

Additional Context: https://github.com/tektoncd/operator/pull/307#discussion_r700872669

**Comment by vdemeester** [comment]
Short answer : Yes 🙃 
It makes little sense to have an inconsistency in what the operator provides on different platforms.

With the concept of profiles, and individual CR (TektonPipeline, …), does it make sense to disable some components for a specific build ?

**Comment by vdemeester** [comment]
We might migrate this to a conversation 😛 but this is still the case.
