### ISSUE TITLE
use operator to install pipeline failed after uninstall it

### ISSUE THREAD

**Issue by XiaoBoya** [tektoncd/operator#409]
# Expected Behavior
1.install pipeline(success)
2.uninstall pipeline(success)
3.install pipeline(success)

# Actual Behaviord
1.install pipeline(success)
2.uninstall pipeline(success)
3.install pipeline(failed)

# Steps to Reproduce the Problem

1.install pipeline
2.uninstall pipeline
3.install pipeline

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

0.24.1

crd for pipeline status:
DependenciesInstalled:unknown
DepploymentsAvailabale:unknown

tekton-pipeline-webhook not found

**Comment by sm43** [comment]
Hi @XiaoBoya, Thank you for reporting issue.
I just have few question
- what version of Operator are you using?
- On which platform are you facing the issue? OpenShift/Kubernetes?
- How are you installing pipelines using `TektonPipeline` CR or `TektonConfig` (which is by default recommended way)

**Comment by XiaoBoya** [comment]
> Hi @XiaoBoya, Thank you for reporting issue.
> I just have few question
> 
> * what version of Operator are you using?
> * On which platform are you facing the issue? OpenShift/Kubernetes?
> * How are you installing pipelines using `TektonPipeline` CR or `TektonConfig` (which is by default recommended way)

0.23.0-2

k8s

apiVersion: operator.tekton.dev/v1alpha1
kind: TektonPipeline
metadata:
  name: pipeline
spec:
  targetNamespace: operators

**Comment by nikhil-thomas** [comment]
@XiaoBoya are you facing this issue with the recent releases
