### ISSUE TITLE
Ability to configure controller cmd line args in operator

### ISSUE THREAD

**Issue by hokadiri** [tektoncd/operator#420]
### Feature request
Implement a way to configure controller cli args in operator.

### Use case

I configure/deploy my pipeline controller via the [release.yaml](https://tekton.dev/docs/pipelines/install/) way. With that, i'm able configure the controller cmd line args e.g [performance cli args](https://tekton.dev/docs/pipelines/tekton-controller-performance-configuration/) or [others](https://github.com/tektoncd/pipeline/blob/main/config/controller.yaml#L65-L87). 

I want to configure/deploy my pipeline controllers using operator. We can only configure the [configmap configs](https://github.com/tektoncd/pipeline/blob/main/docs/install.md#customizing-the-pipelines-controller-behavior).
 There's no way to [configure](https://github.com/tektoncd/operator/blob/386c9138f761ba262bd6479b90c83441d8034977/docs/TektonPipeline.md) the cli args in the operator.

**Comment by nikhil-thomas** [comment]
One way to handle this will be to follow what we do to support imageReplacements. We can support an environment variable  (eg: `CLI_PARAM_TEKTONCD_PIPELINE_CONTROLLER`) on operator controller deployment and use that to modify cli arguments for payload deployments (eg: tektoncd-pipelines-controller)

However, a cleaner way to do this will be to support this as a parameter in TektonConfig spec(per component)

**Comment by ctrought** [comment]
/reopen require custom performance args
/remove-lifecycle rotten require custom performance args

https://tekton.dev/vault/pipelines-v0.44.x-lts/tekton-controller-performance-configuration/

**Comment by ctrought** [comment]
/reopen

https://tekton.dev/vault/pipelines-v0.44.x-lts/tekton-controller-performance-configuration/
