### ISSUE TITLE
Refactor TektonComponent with new refactoring changes

### ISSUE THREAD

**Issue by sm43** [tektoncd/operator#424]
With recent refactoring of Operator, we have disabled `TektonComponent` as we have changed the status 
for components and condtion used in status for them.

We can refactor the `TektonComponent` with the common things which are there in all components now and so that
there will be uniformity between all components method.

Refactoring PRs https://github.com/tektoncd/operator/pull/385, https://github.com/tektoncd/operator/pull/408, https://github.com/tektoncd/operator/pull/421

Update the status methods which are common in status 
https://github.com/tektoncd/operator/blob/039009587fe6bd89f975455a98c39113530f097e/pkg/apis/operator/v1alpha1/common.go#L49

Once dashboard and results start using TektonInstallerSet we can update them otherwise they will break as they still use TektonComponent.

**Comment by nikhil-thomas** [comment]
@sm43 if you think all the reconcilers are ready to accept `TektonComponent` refactoring, then could you add a `help-wanted` label to this issue.

**Comment by sm43** [comment]
> @sm43 if you think all the reconcilers are ready to accept `TektonComponent` refactoring, then could you add a `help-wanted` label to this issue.

once https://github.com/tektoncd/operator/issues/548 is done, we would be able to do that.
