### ISSUE TITLE
Customize config-artifact-pvc

### ISSUE THREAD

**Issue by ronaldslc** [tektoncd/operator#427]
### Feature request

Currently a custom config-artifact-pvc will be overwritten in a situation similar to https://github.com/tektoncd/operator/issues/149 

### Use case

Define default storage class name and size without it being overwritten by operator

**Comment by nikhil-thomas** [comment]
@sm43 Did we take care of this as part of the efforts to expose settings in configMaps through TektonConfig CRD spec
