### ISSUE TITLE
Handling installation of a component when a cluster doesn't support webhooks

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/operator#431]
We need a to disable webhooks while the oeprator is used to install Tekton Components on a Kubernetes Cluster which does not support (or give acces to) webhooks. 

### Use case

- [Validate Tekton works with GKE Autopilot #3798](https://github.com/tektoncd/pipeline/issues/3798)

**Comment by nikhil-thomas** [comment]
One approach to handle this is to add a config field in the TektonConfig CRD to enable/disable webhooks

Ref:
- [TektonConfig CRD example](https://github.com/tektoncd/operator/blob/main/config/crs/kubernetes/config/all/operator_v1alpha1_config_cr.yaml)
- [TektonConfig CRD definition](https://github.com/tektoncd/operator/blob/main/config/base/300-operator_v1alpha1_config_crd.yaml)
- [TektonConfig CRD Spec](https://github.com/tektoncd/operator/blob/4162dd5486444c1e4ec4fe7296f6327a1e96650b/pkg/apis/operator/v1alpha1/tektonconfig_types.go#L66)

**Comment by sm43** [comment]
Does this require that we disable the Operator webhook also?
and from the payload before applying filter out all webhook and its related resources?

**Comment by nikhil-thomas** [comment]
yup, this will have to disable both operator's webhooks and the webhooks from components (triggers, pipelines...) managed by the operator.

**Comment by nikhil-thomas** [comment]
@sm43 may be not all "webhook configurations"

ref: https://github.com/tektoncd/pipeline/issues/3798#issuecomment-932339102
