### ISSUE TITLE
Operator Should Recreate CRDs  (PipelineRun, Task, TriggerBinding...) if they are deleted 

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/operator#433]
### Feature request

At present, the operator reconcilers do not watch CRDs. Therefore if the component CRDs gets deleted for some reason the operator reconcilers will get be notified. We need to make the reconcilers watch CRDs as well so that events on CRDs owned by a components will trigger a reconcile loop.

**Comment by vdemeester** [comment]
What happens if the CRD exists but has been modified (by another component) ? (for example adding new versions, … that are not supported yet) Do we want to handle this or do we stop at re-creating them (meaning, in that case, we would have to delete CRDs.. — which make sense)

**Comment by nikhil-thomas** [comment]
i think it this case, we stick to our genereal policy: 'the operator resets to safe tested defaults' 🧑‍💻 😇
