### ISSUE TITLE
tektoncd operator working with podman on a MAC.

### ISSUE THREAD

**Issue by rhatdan** [tektoncd/operator#448]
Could tekton search for container registries login information in both
~/.config/containers/auth.json as well as ~/.docker/config.json since Podman on a MAC uses this location for storing its credentials.
This would fix this bug.
https://github.com/containers/podman/issues/11923

**Comment by imjasonh** [comment]
[Looking at the code](https://github.com/google/go-containerregistry/blob/72ae53c6cd6746b48ee64f08aa8b504d4d975a00/pkg/authn/keychain.go#L65), you should be able to workaround this in the meantime by setting `DOCKER_CONFIG=~/.config/containers/auth.json`.
