### ISSUE TITLE
Allow unknown resources to install if predicate is not defined in TektonInstallerSet

### ISSUE THREAD

**Issue by sm43** [tektoncd/operator#496]
Currently, in TektonInstallerSet we define predicates for all resources we want to install throught TektonInstallerSet
for example.
https://github.com/tektoncd/operator/blob/35c7ea4f3e55bf2a655f8b9357dd3be58017fdbe/pkg/reconciler/kubernetes/tektoninstallerset/install.go#L31

but if a resource is newly added in release yaml or we define in any Tekton Component reconciler and pass to InstallerSet.
It will not be installed unless we define a predicate for it.

so, to handle any new platform specific resource we can define a new condition at end of reconciler where we install all remaining resource which were not installed.

but what if a new k8s cluster scope resource is added new ly? 
do we install it at last with remaining resource?

if we can check if a resource is cluster scope or namespace scope someway then we don't need to list any resource
we check if CRD -> install
then
if clusterscope -> install
 but to check clustescope we have listed all resources, if we can find a way to check if a k8s resource is clusterscope then this can get a bit easier..
 
 and any unknown resource/ platform specific can be installed at last.

**Comment by nikhil-thomas** [comment]
Note: this PR https://github.com/tektoncd/operator/pull/542 depends on the "Feature" addressed by this issue. 
That is the pr filters out PodSecurity policy with the expectation that no "Finally"or "Defalult"case down the road will create it. 

> at least, we should make sure that, if a resource is filtered during the installation of the operator, we highlight it in the logs (aka, it's very visible)

@vdemeester 
I agree.
So I think a decent compromise for handling this situation is to log it and if possible mention the items which were "not installed" in TektonInstallerSet status.
