### ISSUE TITLE
Issue: Missing or invalid Task test/s2i-buildah-push: translating Build to Pod: serviceaccounts

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/operator#50]
## Issue

I'm getting a very strange `TaskRun` message --> see

```
message: 'Missing or invalid Task test/s2i-buildah-push: translating
Build to Pod: serviceaccounts "build-bot" not found'
```

even if the serviceaccount exists like the task and taskruns

https://gist.github.com/cmoulliard/28cede49e8a2ea69531aa814ded10307#file-gistfile1-txt-L67

**Comment by vincent-pli** [comment]
@cmoulliard 
I guess you post issue in wrong place, should in `pipeline`.
anyway, the error is complain the `serviceaccount: build-bot` is not found, when `pipeline` try to create `pod` based your `task` definition.

**Comment by sthaha** [comment]
@cmoulliard could you please file this against [pipeline](https://github.com/tektoncd/pipeline/issues/new)

**Comment by cmoulliard** [comment]
Ticket created under pipeline project
