### ISSUE TITLE
README says 0.5.0 is installed?

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/operator#51]
# Expected Behavior

Installing the operator installs a recent Tekton (based on https://github.com/tektoncd/operator/commit/1ffa6513820d3d503464cae397c89d249e3b5d0d that's 0.7.0?), and that version is documented upfront.

...or the specific version _isn't_ documented upfront, and documentation just says "a recent Tekton will be installed"

# Actual Behavior

README.md says:

> The Operator will automatic install `Tekton pipeline` with `v0.5.2` in the namespace `tekton-pipeline`

**Comment by vincent-pli** [comment]
@ImJasonH 
Thanks, I think we need correct the README.md after version upgrade.

**Comment by nikhil-thomas** [comment]
fixed in https://github.com/tektoncd/operator/pull/52
