### ISSUE TITLE
Helm chart for installing Tektoncd using Tektoncd/operator

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/operator#543]
At present, 2 ways to install Tektoncd/operator are:

- kubectl apply <githhub relese.yaml>
- from operatorhub.io (for this a user will have to install [OperatorLifecycleManager](https://github.com/operator-framework/operator-lifecycle-manager) on a cluster first)

I think providing a helm chart for operator will be an improvement compared to the available options, as it would help us leverage an existing popular tooll

Refer:

- https://github.com/tektoncd/pipeline/issues/1542#issuecomment-817854900

**Comment by nikhil-thomas** [comment]
Related to https://github.com/tektoncd/operator/issues/287

**Comment by dirien** [comment]
Hi @nikhil-thomas, if you need help let me know! I am so looking forward to this!

**Comment by nikhil-thomas** [comment]
copy that 🧑‍💻 👍

**Comment by jacksgt** [comment]
This issue can be closed as it was fixed with https://github.com/tektoncd/operator/pull/627
