### ISSUE TITLE
Add labels-exclusion-pattern feature flag for triggers in Operator 

### ISSUE THREAD

**Issue by sm43** [tektoncd/operator#546]
Triggers has a new field in feature config map `labels-exclusion-pattern` which isn't there in TektonConfig or TektonTrigger CR for users to configure it.

new field: https://github.com/tektoncd/triggers/blob/aa30266234055e5d8aa373551e27f7ca885390e7/config/config-feature-flags.yaml#L29

Reference:
https://github.com/tektoncd/operator/pull/411

/help-wanted
/good-first-issue

**Comment by ShivamTyagi12345** [comment]
I would like to help with this issue

**Comment by sm43** [comment]
hi @ShivamTyagi12345 sure. Thank you 🙂 
I will assign this to you.
/assign @ShivamTyagi12345 
Please go through https://github.com/tektoncd/operator/pull/411 this is similar to what we need to do for this issue.
- We need to add a new filed for `labels-exclusion-pattern` [here](https://github.com/vinamra28/operator/blob/7ec2c86447da47d6a3ec227ffcfa87e29f4959c9/pkg/apis/operator/v1alpha1/tektontrigger_types.go#L84) 
```
	LabelsExclusionPattern       string `json:"labels-exclusion-pattern,omitempty"`
```
let me know if you get have questions. 🙂

**Comment by sm43** [comment]
@ShivamTyagi12345 would you be able to do this? or can we unassign you so that someone else can do it?

**Comment by camperjett** [comment]
Hey @sm43 I would like to work on this issue. Could you please help me get started with it?
