### ISSUE TITLE
The tekton-pipelines namespace is not deleted after delete the config CR

### ISSUE THREAD

**Issue by zhangtbj** [tektoncd/operator#55]
# Expected Behavior
The tekton-pipelines namespace is deleted after delete the config CR

# Actual Behavior
The tekton-pipelines namespace is not deleted after delete the config CR

# Steps to Reproduce the Problem
1. Start the tekton operator
2. Apply the config cr
3. delete the config cr

# Additional Info
All resources in the tekton-pipelines namespace are deleted. But the namespace is still there. it should also be deleted I think.

**Comment by vincent-pli** [comment]
@zhangtbj 
The `tekton-pipelines` will be deleted when `config` cr deleted, just make sure the ns: `tekton-pipelines` is created by `Operator` rather than created manually.

**Comment by zhangtbj** [comment]
Oh cool, @vincent-pli ,

Yes, it is deleted if the namespace is created by the operator.

Thanks a lot!
