### ISSUE TITLE
Received may Failed to list *unstructured.Unstructured error in operator pod log

### ISSUE THREAD

**Issue by zhangtbj** [tektoncd/operator#56]
# Expected Behavior
No related error log.

# Actual Behavior
there is no error log when using local debug mode. But when I generated operator image and deploy officially, I received many error logs like:
```
E1127 07:26:09.322598       1 reflector.go:134] github.com/operator-framework/operator-sdk/pkg/kube-metrics/collector.go:67: Failed to list *unstructured.Unstructured: the server could not find the requested resource
E1127 07:26:09.324121       1 reflector.go:134] github.com/operator-framework/operator-sdk/pkg/kube-metrics/collector.go:67: Failed to list *unstructured.Unstructured: the server could not find the requested resource
E1127 07:26:10.328979       1 reflector.go:134] github.com/operator-framework/operator-sdk/pkg/kube-metrics/collector.go:67: Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

# Steps to Reproduce the Problem

1. Build and push image to docker hub
2. modify the operator yml to use this image
3. kubectl apply and check log: `kubectl log <operator pod> -n tekton-operator

# Additional Info

**Comment by addozhang** [comment]
same here

**Comment by vincent-pli** [comment]
I think this issue is from `operator-sdk`, seems still not resolve:
https://github.com/operator-framework/operator-sdk/issues/1858

**Comment by vincent-pli** [comment]
Fixed
