### ISSUE TITLE
no limit for tektonpipeline cr name

### ISSUE THREAD

**Issue by XiaoBoya** [tektoncd/operator#562]
### Feature request

Will the limitation of cr name during installation of tektonpipeline be removed in the future?

### Use case

I want to add the tekton operator to the operatorhub on the intranet, but I need to fill in the cr name when instantiating it. If there is no restriction that the name must be 'pipeline', then I do not need to process the data in this input box with special rules.

**Comment by nikhil-thomas** [comment]
Most probably, No, the limitation will not be removed in the future.

## More context:

- This limitation is our attempt to implement a "Singleton CRD" (a cluster wide CRD which can only have one valid instance on a cluster). We need this to make sure that there is only 1 set of Tekton-Pipelines (for example) controller and webhook on a cluster. At present, Tekton-Pipelines controler and webhook watches all namespaces so having more than one instances of those will be messy.

- In the future, if TektonPipelines start supporting multinamespace installations, ie, Controller in namespace `tekton-pipelines-1` watches `namespaceA`, `namespaceB`, `namespaceC` and controlller in namespace `tekton-pipelines-2` watches all the other namespaces, then we will have to remove this limitation.

- At present, TektonPipelienes controller can be configured to watch [AllNamespaces or a SingleNamespace](https://github.com/tektoncd/pipeline/blob/2ee13837eaee98ec19b5ca5e53e19d9e532433b6/cmd/controller/main.go#L45). I cannot be configured to watch a set of `n` namespaces.

**Comment by XiaoBoya** [comment]
thanks for reply

**Comment by nikhil-thomas** [comment]
cc @sm43 @vdemeester
