### ISSUE TITLE
Coloured Logs for Tekton Operator

### ISSUE THREAD

**Issue by PuneetPunamiya** [tektoncd/operator#567]
### Feature request

Currently operator logs have no color, hence it becomes difficult to debug by reading the logs

So based on the mode, i.e. Production or Development we can have colored logs for the development mode
where it becomes easy to read the logs and for the production logs we can have the same it as we have now

For example : 

![image](https://user-images.githubusercontent.com/32545638/146773072-f05b15e4-3349-42ac-ac64-e03df64a74c1.png)

**Comment by nikhil-thomas** [comment]
This will greatly help with debugging. @PuneetPunamiya if you are working on it, could you assign this issue to yourself. If not, could you add `help-wanted` label.

In addition, could you link in this issue thread relevant pull requests from [tektoncd/hub](https://github.com/tektoncd/hub) (and/or other relevant resources).

## How about "Coloring based on reconcilers as well" 

can we do coloring to indicate which reconciler created a log. I think it will greatly help us focus on log messages that we are interested in while working on a particular reconciler.

**Comment by PuneetPunamiya** [comment]
The idea regarding "Coloring based on reconciler as well" sounds great 👍🏻

**Comment by vdemeester** [comment]
https://github.com/chmouel/sugarjazy helps a bit here 👼🏼

**Comment by vdemeester** [comment]
I am going to close this issue as "wontfix" as I feel it's not up to the operator, but to consumer of the logs to implement this. With sugarjazy or [`snazy`](https://github.com/chmouel/snazy/), this is already possible.
