### ISSUE TITLE
Change tektonVersion to a command flag so that user can choose the tekton verision

### ISSUE THREAD

**Issue by zhangtbj** [tektoncd/operator#57]
# Expected Behavior
User can use `--version v0.7.0` to use different tekton version to install

# Actual Behavior
`tektonVersion   = "v0.8.0"` version is hardcode in config controller

User cannot choose the version, just use the default `v0.8.0` version now.

It is better to set it a parameter. then we can use it for the upgrade or future version maintain

**Comment by vincent-pli** [comment]
@zhangtbj 
You can use 
```
args:
- --resource-dir=deploy/resources/v0.7.0
```
to achieve this, it's more flexible than just `version`, could handle the case that user want to use arbitrary version.

**Comment by zhangtbj** [comment]
Thanks @vincent-pli !

So is this arg `resource-dir` works for upgrade?

For example I installed the tekton version `v0.7.0` by using operator with `- --resource-dir=deploy/resources/v0.7.0`. Then I would like to upgrade the version to `v0.8.0`.
What should I do next?

Restart the operator and reset the parameter to `- --resource-dir=deploy/resources/v0.8.0` ?

**Comment by vincent-pli** [comment]
I'm afraid it's not work, you need do the uninstall and re-install :)

**Comment by zhangtbj** [comment]
em.... :(

I am still not clear about the upgrade path.

Hope you can have some doc to show how to do it in future.

Anyway, thanks a lot @vincent-pli :)

**Comment by zhangtbj** [comment]
Hi @vincent-pli ,

I re-opened this issue again.

Right now, the config cr only has one spec parameter `TargetNamespace`:
https://github.com/tektoncd/operator/blob/master/pkg/apis/operator/v1alpha1/config_types.go#L11

I am not sure why you want to use the operator execution parameter to set the release version.

But only set the release version in the CRD spec definition. 

I think if you add a new config CRD spec definition parameter like `TargetReleaseVersion`, it is better for end user to modify or find it or maybe upgrade in future.

operator command parameter is not a good way I think ....

**Comment by vincent-pli** [comment]
hum, yes, it's make sense in upgrade scenario.
Seems we have not consider too much for the upgrade.
/cc @vdemeester @sthaha @nikhil-thomas @houshengbo

**Comment by sthaha** [comment]
We should discuss this in more detail in the WG meeting. 

IMHO, `--version` or `--resourcedir` is useful only in dev environments and not in production where the expectation is that the operator is installed through `OLM` (operatorhub.io) (sidenote: we need to ship this operator to operatorhub.io 🙏) 

So in the case where user installs pipeline through operator, the k8s way to install a different version would be to make use of `cluster` (CR) `config.operator.tekton.dev` and add field to it say: `version: "0.7.0"` but this presents its own challenges as often the controller code makes assumptions about the default version of the pipeline being installed and we might be able to solve this by delegating the "configuration" part to an object specific to the version of the pipeline installed but before we go that path, we should try the mechanism that OLM already provides 

OLM (operatorhub.io) provides a way to upgrade (manual/auto) an  operator and our experience writing the operator for OpenShift is that using the mechanism to upgrade the operator works without any hassles and imho we should rely on just that and not on `config.tekton.dev` or `--version` as a way to install different versions of pipeline. OLM  support the upgrade path seamlessly, to provide an upgrade all we have to do is to provide the `CSV` to the community operators repo.

**Comment by zhangtbj** [comment]
Thanks all!

Please document somewhere that other people can know and review this requirement design.

Thanks a lot!
