### ISSUE TITLE
Running each controller as a separate container

### ISSUE THREAD

**Issue by sm43** [tektoncd/operator#576]
Currently, we run all controller in a single container
https://github.com/tektoncd/operator/blob/main/cmd/kubernetes/operator/main.go
as we are adding new components the logs are getting more and more an it is getting difficult to debug and understand them.

We can run one controller per container
so
- one container for TektonConfig running its controller,
- one for TektonPipeline running its controller, and similar for others.
This would separate logs and makes debugging easier.

We can have same image, based on some flag or env it can start a particular controller

**Comment by sm43** [comment]
cc @vdemeester @nikhil-thomas

**Comment by nikhil-thomas** [comment]
I think it is a great idea. I think this will greatly improve developer experience.

With the addition of TektonInstallerSet, the component lifecycle logs (something not found, fresh install, dependencies met...) come from individual component reconcilers and cluster operation logs (created, updated, deleted etc) comes from TektonInstallerSet reconciler logs. 

👨‍💻 So even if we move just the TektonReconcilerSet reconciler into a new container (same image/executable but with a flag switch), the lifecycle logs and cluster operation logs will be neatly separated from a `kubectl logs` prespective.

ie, even if we do not split each of our 'n' reconcilers into a separate container, moving the TektonInstallerSet reconciler into a new container alone could be a huge improvement of debugging experienece.

In addition, the [colored logs efforts](https://github.com/tektoncd/operator/issues/567) will make more sense with the change proposed by this issue.

cc @PuneetPunamiya

**Comment by nikhil-thomas** [comment]
/remove-lifecycle stale

being addressed by https://github.com/tektoncd/operator/pull/710

**Comment by vdemeester** [comment]
I'll close this as we splitted the operator into 2 containers, and that should be enough for now.
