### ISSUE TITLE
How to upgrade/downgrade CR for operator

### ISSUE THREAD

**Issue by gyliu513** [tektoncd/operator#60]
I found that the opertor is creating CR at https://github.com/tektoncd/operator/blob/e8cf87e/pkg/controller/config/config_controller.go#L121-L124 , so my question is how to handle the case of upgrade or downgrade for the CR in the operator?

FYI @clyang82 @vincent-pli @houshengbo @chenzhiwei

**Comment by vincent-pli** [comment]
Based on current implements the original `cr` will be reused,
after installation it will be mark as new version in `status`, like this:
```
status:
  conditions:
  - code: installed
    version: v0.9.0
```
I have no idea if `CRD` changed, for example the `version` change to `v1beta1`, I guess the original `cr` will be leave there and new `cr` will be create.

@sthaha Could OLM help on this part?
