### ISSUE TITLE
Make all used images configurable

### ISSUE THREAD

**Issue by Obirah** [tektoncd/operator#610]
### Feature request

Currently the tekton operator and all the components it deploys use images from gcr.io - of course, this should remain the sane default, however when using the operator in an enterprise environment one needs to change the images so that mirrors can be used.

### Use case

In our corporate environment we use Artifactory in order to use remotes of the big image repositories like Docker Hub, gcr, quay and so on. As a workaround gcr.io can be accessed through a proxy, but it is highly encouraged by our security/compliance guidelines to use our remotes instead of directly accessing the repositories.

**Comment by nikhil-thomas** [comment]
This is currently doable in operator by setting environment variables. We do this while creating operator releases which is made available on Red Hat OpenShift.

Currently we can override images by setting environment variables like [this](https://github.com/tektoncd/operator/blob/e7b2e98e1993bf7522381ab160bbed43a1f4367a/operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml#L807) in the operator controller deployment.

I shall document this better.

**Comment by Obirah** [comment]
Cool, thank you for the information, that eases some pain! :) However, mid- and long-term I think it would be cooler to be able to configure this through custom resources. In my opinion the [ArgoCD operator](https://argocd-operator.readthedocs.io/en/latest/reference/argocd/) is a good example on how to approach this topic.

**Comment by DarthBlair** [comment]
> This is currently doable in operator by setting environment variables. We do this while creating operator releases which is made available on Red Hat OpenShift.
> 
> Currently we can override images by setting environment variables like [this](https://github.com/tektoncd/operator/blob/e7b2e98e1993bf7522381ab160bbed43a1f4367a/operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml#L807) in the operator controller deployment.
> 
> I shall document this better.

Thanks! 
At the moment we are unable to identify the env variable for changing the dashboard image. Does anyone have a hint or solution for that as well?

**Comment by Oded-B** [comment]
> This is currently doable in operator by setting environment variables. We do this while creating operator releases which is made available on Red Hat OpenShift.

Does the fact that those env vars are missing from the [k8s bundle config](https://github.com/tektoncd/operator/blob/main/operatorhub/kubernetes/config.yaml) means they wouldn't work with the k8s operator in its current form?
