### ISSUE TITLE
Add External Logs feature for dashboard in Tekton Config

### ISSUE THREAD

**Issue by srisek** [tektoncd/operator#623]
### Feature request

Request to add a feature in Tekton Config CRD to allow configuration of external logs for tekton dashboard.

### Use case

I am currently installing Tekton dashboard using Tekton operator. It would be good if, tekton config CRD can accept external logs as a spec field that will enable to configure URL for external logs, to avoid manual update of the configMap.

apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  namespace: tekton-operator
spec:
  profile: all
  targetNamespace: tekton-pipelines
  dashboard:
    readonly: true
    externalLogs: <<URL>>

Currently there is no spec to configure external logs in TektonConfig.

**Comment by mike-serchenia** [comment]
could we reopen the feature request please ?

**Comment by srisek** [comment]
I would also the second the same, this would be a good to have this incorporated into the operator. Currently I had to install dashboard from the manifest directly outside the scope of using the operator and updated the deployment spec to configure the external logs flag using kustomize.

**Comment by AlanGreene** [comment]
@tektoncd/operator-maintainers we've had another few users request this in the past week. Can we get this reopened please?
