### ISSUE TITLE
Support custom registry for components

### ISSUE THREAD

**Issue by kaos** [tektoncd/operator#625]
### Feature request

In order to deploy Tekton from images pushed to a private registry, we need a way to configure Tekton Operator to deploy components referring to these internal images rather than the publicly hosted ones.

### Use case

Running a k8s cluster isolated from the public internet, we can not deploy services based on images pulled off of public registries.

Related issue: #66 (bullet 1)

**Comment by nikhil-thomas** [comment]
currently there exists a hacky weakly documented way. We can set environment variables like [this](https://github.com/tektoncd/operator/blob/abad3531bf90b15dd64daaa27a5480647dd37114/config/openshift/base/operator.yaml#L69) or [this](https://github.com/tektoncd/operator/blob/abad3531bf90b15dd64daaa27a5480647dd37114/operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml#L808) and override the default images.

However, the ux for this approach is not great. We are open to suggestions. What kind of ux will you suggest? 
for example:
- additiona configuration in tektonconfig instance
- a new configMap with list of image overrides

**Comment by kaos** [comment]
Ah, great. That is a good first step. What would be great is an authoritative list of all images used, and their default values (so we can be sure to include/override them all).

We'd generate this, so using env vars or config map I don't think is any major difference in ux. I may come up with better suggestions once we get a bit more experience trying this out.

**Comment by ktarplee** [comment]
I think having the map of image overrides in the tektonconfig is the way to go.  It allows for air-gapped environments where the syncing process might not preserve manifest IDs.

**Comment by r67yfyt** [comment]
Any pr or feature fix this?
