### ISSUE TITLE
One operator for all deployments

### ISSUE THREAD

**Issue by kaos** [tektoncd/operator#626]
### Feature request

Support deploying multiple instances of Tekton components (in different namespaces). That is, support using multiple `TektonConfig` resources in a single operator deployment.

### Use case

We want to be able to use Tekton for several disjoint use cases, that are isolated from each other. Deploying the Tekton components to multiple namespaces solves this, but it would be preferable to not have to use a dedicated Operator for each namespace.

**Comment by nikhil-thomas** [comment]
This is an interesting issue. This could be implemented if other tektoncd projects can take a list of namespaces to watch as an argument. 

At present, tektoncd/pipeline supports only an `all or one` approach. refer [this](https://github.com/tektoncd/pipeline/blob/38d98f09ecdd5240d91762ff6a75bc6275316ed9/cmd/controller/main.go#L46) . The namespace flag in pipeline controller do not accept a list of namespaces.

Once tektoncd/pipeline supports this feature, we plan the support for this on high priority.

### related issues
- https://github.com/tektoncd/pipeline/issues/4307

**Comment by kaos** [comment]
> At present, tektoncd/pipeline supports only an all or one approach.

From my perspective, the `one` namespace approach is sufficient here, as I expect we'd deploy multiple instances (one per namespace) of tektoncd/pipeline, so each instance will only ever be concerned with that single namespace where it is deployed.
