### ISSUE TITLE
Ability to add custom labels to resources

### ISSUE THREAD

**Issue by Miles-Garnsey** [tektoncd/operator#651]
### Feature request

We have a service mesh in place in our cluster which relies on the ability to label namespaces and workloads (pods) to configure it. 

To get Tekton running on the mesh, we need to be able to label:

1. The namespace created by tekton-operator (`targetNamespace`)
2. The various controllers created in that namespace (tekton-dashboard, tekton-operator-proxy-webhook, tekton-pipelines-controller, tekton-pipelines-webhook, tekton-triggers-controller, tekton-triggers-core-interceptors, tekton-triggers-webhook).

### Use cases

There are many: Service mesh sidecar injection, as mentioned above. Reporting on workloads running in the cluster, OPA rule compliance, some types of affinity/anti-affinity, kubernetes NetworkPolicy.

**Comment by nikhil-thomas** [comment]
This is an interesting idea. The challenge now is that the deployment gets reset to initial state, if the operator detects that the deployment has changed on cluster. So if we are supporting this we will also have to make sure that the operator is tolerant to certain changes (eg: adding additional labels)

**Comment by Miles-Garnsey** [comment]
> This is an interesting idea. The challenge now is that the deployment gets reset to initial state, if the operator detects that the deployment has changed on cluster. So if we are supporting this we will also have to make sure that the operator is tolerant to certain changes (eg: adding additional labels)

I'd suggest that you should add `labels:` fields into the operator's CRD so that users can define the labels from there. Having to define them as a second step after the resources are created could present problems in some (e.g. GitOps) scenarios.
