### ISSUE TITLE
Provide ability to disable namespace creation

### ISSUE THREAD

**Issue by Miles-Garnsey** [tektoncd/operator#652]
### Feature request

It seems that there is no way to prevent the operator from trying to create its own namespace. It would be good if it was possible to turn this behaviour off.

### Use case

Two use cases:
1. In some RBAC configurations non-admin users do not have the ability to create namespaces.
2. If the namespace already exists, it will be overwritten by the operator's namespace. This can cause quite problematic issues if the namespace has been configured with labels, annotations, or other metadata that needs to be retained.

**Comment by nikhil-thomas** [comment]
This is something we never gave much thought 😇 🧑‍💻 . This is a very valid use case.

> In some RBAC configurations non-admin users do not have the ability to create namespaces.

i do support this use case.
may be we can add a configuration in TektonConfig CRD spec to disable namespace creation.

In addition, we will need to brainstorm all scenarios this will need to support (installation/upgrade/uninstallation...)

> If the namespace already exists, it will be overwritten by the operator's namespace. This can cause quite problematic issues if the namespace has been configured with labels, annotations, or other metadata that needs to be retained.

this is a tricky situation. this operator assumes that the targetnamespace and other namespace scoped resources are dispossable (~stateless). ie, it can delete/recreate those resources at will. This is an assumption we follow to make upgrades less flaky (inplace upgrade vs delete-recreate upgrade)

So to support this usecase we have to make sure that we don't make our upgrades less stable or less predictable.

cc @sm43

**Comment by Miles-Garnsey** [comment]
> this is a tricky situation. this operator assumes that the targetnamespace and other namespace scoped resources are dispossable (~stateless). ie, it can delete/recreate those resources at will. This is an assumption we follow to make upgrades less flaky (inplace upgrade vs delete-recreate upgrade)

It sounds as though you're currently deleting the whole namespace and re-creating? Would it be viable to retrieve the operator's objects by label and delete those under it's control, rather than trying to use the namespace to identify them?
