### ISSUE TITLE
Tekton operator security improvements

### ISSUE THREAD

**Issue by davidkarlsen** [tektoncd/operator#66]
# Expected Behavior

1. operator creates tekton-pipelines-controller and tekton-pipelines-webhook deployments, but it should be possible to define a custom registry for the images (to use in air-gap envs)
2. securityContext for the deployments should be configurable, as of now they are `{}` - which means root, privileged, etc

# Actual Behavior

# Steps to Reproduce the Problem

1. install the standard tekton operator using current defined config

# Additional Info

**Comment by vincent-pli** [comment]
@davidkarlsen 
So, these are two requirements.

For the first one: `custom registry`, I personal prefer the design in [knative/serving-operator](https://github.com/knative/serving-operator/blob/5897cd8d8238eebfbeed7305b3e86a462f716b35/pkg/apis/serving/v1alpha1/knativeserving_types.go#L85), they defined a map to replace related image url in the `yaml`s, also consider the `pullsecret`, I think we can follow the same design.
@vdemeester @houshengbo @sthaha @nikhil-thomas

**Comment by sthaha** [comment]
I agree, it will nice to use a config-map that we can use to `manifest.Transform` images that matches a regex to a destination image.
