### ISSUE TITLE
Why are OpenShift images based on RHEL8 instead of UBI8?

### ISSUE THREAD

**Issue by fgiloux** [tektoncd/operator#676]
### Feature request

Using images based on UBI: like registry.access.redhat.com/ubi8/buildah instead of images based on RHEL8 like: registry.redhat.io/rhel8/buildah

### Use case

Images based on RHEL8 are bound to RHEL EULA, which limits redistribution. This restriction does not apply to UBI8 images.
A consequence is that registry.redhat.io requires authentication. registry.access.redhat.com does not.
Images based on RHEL8 need to run on machines having RHEL subscriptions. This is not the case for UBI8 images.

**Comment by vdemeester** [comment]
Note: if upstream OpenShift release such as [here](https://github.com/tektoncd/operator/releases/tag/v0.54.0) are using RHEL, then this should be considered as a bug.

**Comment by vdemeester** [comment]
Ah it's only for few images, such as the `buildah` image, I see. Then I tend to agree.
I've checked, all of the component and operator images are based on top of ubi8, only few like the buildah one are not.

**Comment by vdemeester** [comment]
`tektoncd/operator` is gonna change a bit early 2023 and the openshift part will be split, *but* it's still a valid point to fix indeed.
