### ISSUE TITLE
Error in Tekton operator image while upgrading to v0.55.0

### ISSUE THREAD

**Issue by srisek** [tektoncd/operator#681]
# Issue

Upgrade to tekton operator version v0.55.0.

The tekton operator container is failing with the below error.

Error:

**_Terminated - Error (exit code: 2)_**

**panic: open /var/run/ko/tekton-pipeline: no such file or directory**

# Container Log

2022/03/14 15:05:28 Registering 3 clients
2022/03/14 15:05:28 Registering 3 informer factories
2022/03/14 15:05:28 Registering 10 informers
2022/03/14 15:05:28 Registering 8 controllers
{"level":"info","caller":"logging/config.go:116","msg":"Successfully created the logger."}
{"level":"info","caller":"logging/config.go:117","msg":"Logging level set to: debug"}
{"level":"info","caller":"logging/config.go:79","msg":"Fetch GitHub commit ID from kodata failed","error":"open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","logger":"tekton-operator","caller":"profiling/server.go:64","msg":"Profiling enabled: false","knative.dev/pod":"tekton-operator-5cf95588df-wnccj"}
{"level":"info","logger":"tekton-operator","caller":"leaderelection/context.go:46","msg":"Running with Standard leader election","knative.dev/pod":"tekton-operator-5cf95588df-wnccj"}
{"level":"info","logger":"tekton-operator.manifestival","caller":"manifestival@v0.7.0/manifestival.go:72","msg":"Parsing manifest","knative.dev/pod":"tekton-operator-5cf95588df-wnccj"}
{"level":"debug","logger":"tekton-operator","caller":"tektonconfig/controller.go:141","msg":"Creating event broadcaster","knative.dev/pod":"tekton-operator-5cf95588df-wnccj"}
{"level":"info","logger":"tekton-operator","caller":"tektonconfig/controller.go:80","msg":"Setting up event handlers for TektonConfig","knative.dev/pod":"tekton-operator-5cf95588df-wnccj"}
{"level":"debug","logger":"tekton-operator","caller":"tektonconfig/instance.go:66","msg":"ensuring tektonconfig instance","knative.dev/pod":"tekton-operator-5cf95588df-wnccj"}
{"level":"info","logger":"tekton-operator.manifestival","caller":"manifestival@v0.7.0/manifestival.go:72","msg":"Parsing manifest","knative.dev/pod":"tekton-operator-5cf95588df-wnccj"}
**panic: open /var/run/ko/tekton-pipeline: no such file or directory**
goroutine 1 [running]:
github.com/tektoncd/operator/pkg/reconciler/common.latestRelease(...)
github.com/tektoncd/operator/pkg/reconciler/common/releases.go:174
github.com/tektoncd/operator/pkg/reconciler/common.TargetVersion({0x1d9f550, 0x0})
github.com/tektoncd/operator/pkg/reconciler/common/releases.go:46 +0x5e
github.com/tektoncd/operator/pkg/reconciler/common.TargetManifest({0x1d9f550, 0x0})
github.com/tektoncd/operator/pkg/reconciler/common/releases.go:51 +0x5f
github.com/tektoncd/operator/pkg/reconciler/common.AppendTarget({0x1ae6e51, 0xc000a2d0e0}, 0xc00078cac0, {0x1d9f550, 0x0})
github.com/tektoncd/operator/pkg/reconciler/common/stages.go:51 +0x4c
github.com/tektoncd/operator/pkg/reconciler/common.Controller.fetchSourceManifests({0xc00078cac0, 0xc00012c788, {0x1ae6e51, 0x2}}, {0x1d46838, 0xc000481f80}, {0xff})
github.com/tektoncd/operator/pkg/reconciler/common/initcontroller.go:95 +0x85
github.com/tektoncd/operator/pkg/reconciler/common.Controller.InitController({0x0, 0xc00012c788, {0x1ae6e51, 0x4200000000000000}}, {0x1d46838, 0xc000481f80}, {0x40})
github.com/tektoncd/operator/pkg/reconciler/common/initcontroller.go:70 +0x60c
github.com/tektoncd/operator/pkg/reconciler/kubernetes/tektonpipeline.NewExtendedController.func1({0x1d46838, 0xc000481f80}, {0x1, 0xc000396780})
github.com/tektoncd/operator/pkg/reconciler/kubernetes/tektonpipeline/controller.go:54 +0x9a
github.com/tektoncd/operator/pkg/reconciler/kubernetes/tektonpipeline.NewController({0x1d46838, 0xc000481f80}, {0x1d33c48, 0xc0002404e0})
github.com/tektoncd/operator/pkg/reconciler/kubernetes/tektonpipeline/controller.go:41 +0x53
knative.dev/pkg/injection/sharedmain.ControllersAndWebhooksFromCtors({0x1d46838, 0xc000481f80}, 0x1, {0xc000a8ff30, 0x8, 0x77359400})
knative.dev/pkg@v0.0.0-20211206113427-18589ac7627e/injection/sharedmain/main.go:390 +0x15c
knative.dev/pkg/injection/sharedmain.MainWithConfig({0x1d471a0, 0xc000650008}, {0x1ae8772, 0xf}, 0xc0003a8b40, {0xc00073ff30, 0x8, 0x8})
knative.dev/pkg@v0.0.0-20211206113427-18589ac7627e/injection/sharedmain/main.go:232 +0x5da
knative.dev/pkg/injection/sharedmain.MainWithContext({0x1d471a0, 0xc000650008}, {0x1ae8772, 0xf}, {0xc00073ff30, 0x8, 0x8})
knative.dev/pkg@v0.0.0-20211206113427-18589ac7627e/injection/sharedmain/main.go:171 +0xe7
knative.dev/pkg/injection/sharedmain.Main({0x1ae8772, 0xf}, {0xc00073ff30, 0x8, 0x8})
knative.dev/pkg@v0.0.0-20211206113427-18589ac7627e/injection/sharedmain/main.go:108 +0x8f
main.main() github.com/tektoncd/operator/cmd/kubernetes/operator/main.go:32 +0xb5

- Kubernetes version:  **1.21**

Observed this error while upgrading from v0.54.0 to v0.55.0. Seems like some files are missing in the operator image with the new release.

**Comment by nikhil-thomas** [comment]
fixed in v0.55.1 release 
https://github.com/tektoncd/operator/releases/tag/v0.55.1

@srisek Thanks for reporting 🧑‍💻 👍

**Comment by nikhil-thomas** [comment]
The reason for this issue was a glictch in the release pipeline.

closing this issue. we shall reopen it if needed.
/close
