### ISSUE TITLE
Support a specific namespace installation mode on the openshift cluster

### ISSUE THREAD

**Issue by tightime** [tektoncd/operator#718]
### Feature request

1. Set **installModes.supported** of **SingleNamespace** type to **true** from **false** in CSV resource file;
2. Set **valueFrom.fieldRef.fieldPath** of **SYSTEM_NAMESPACE** env to **metadata.annotations['olm.targetNamespaces']** from **metadata.namespace** in controller deployment file;

### Use case

It's necessary for this installation mode when the tenant has no admin permission of cluster scope or cann't be disturbed by other tanants.

**Comment by nikhil-thomas** [comment]
It is hard to make commitments like this in the csv present in this repository. However, it is straight forward to generate an new csv (bundle) using the scripts provided in this repository.

for example, if it is required to support singleNamespace installMode, then change that in this csv seed file [here](https://github.com/tektoncd/operator/blob/f0305b52b42bdf30439f9dcff23a760bbb6ee444/operatorhub/kubernetes/manifests/bases/tektoncd-operator.clusterserviceversion.template.yaml#L204) and then generate a bundle using [this](https://github.com/tektoncd/operator/tree/main/operatorhub#quick-links)

I shall gladly answer any question on our csv generation tool. [here](https://github.com/tektoncd/operator/blob/main/operatorhub/tools/bundle.py)

**Comment by tightime** [comment]
> It is hard to make commitments like this in the csv present in this repository. However, it is straight forward to generate an new csv (bundle) using the scripts provided in this repository.
> 
> for example, if it is required to support singleNamespace installMode, then change that in this csv seed file [here](https://github.com/tektoncd/operator/blob/f0305b52b42bdf30439f9dcff23a760bbb6ee444/operatorhub/kubernetes/manifests/bases/tektoncd-operator.clusterserviceversion.template.yaml#L204) and then generate a bundle using [this](https://github.com/tektoncd/operator/tree/main/operatorhub#quick-links)
> 
> I shall gladly answer any question on our csv generation tool. [here](https://github.com/tektoncd/operator/blob/main/operatorhub/tools/bundle.py)

@nikhil-thomas Thank you very much. Do you think this feature requirement is reasonable or is there any hidden risk?

**Comment by nikhil-thomas** [comment]
There is one major risk. As all the reconcilers in this operator watch clusterWide resources (TektonConfig, TektonPipeline...) irrespective of the InstallMode specified, we will run into a situation where more than one controllers are updating the instance(~s~) of these CRDs. 

note: these CRDs will have only 1 instance per cluster as per the current design.
