### ISSUE TITLE
Create a default 'pipeline' service account to run Tasks

### ISSUE THREAD

**Issue by sbose78** [tektoncd/operator#74]
Expected behaviour: 
When the operator setups up the tekton objects, I would expect a `pipeline` service account in every namespace that I could use to run my tasks instead of having to create one explicitly.

**Comment by vincent-pli** [comment]
@sbose78 
Which `sa` do you mean? the `sa` in namespace where pipeline controller lives?
Every namespace? what about new creating ones?

**Comment by sbose78** [comment]
@vincent-pli Just like every namespace in Kubernetes has a service account called `default` , I'm proposing we add a service account in every namespace called `pipeline` which as per our guidance could be used to run TasksRuns.
