### ISSUE TITLE
Repalce existing IsReady check in TektonAddon with declarative implementation

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/operator#752]
At present, in the TektonConfig OpenShift extension, the code which checks Ready state of TektonAddon uses polling, [here](https://github.com/tektoncd/operator/blob/1406b846022e92f4ac15ec695fb94a1b7b12a221/pkg/reconciler/openshift/tektonconfig/extension/addon.go#L36). This means, the reconciler blocks until the Polling timeout runs out or the check succeeds.

Similar checks for TektonPipeline and TektoAddon are handled in a declarative way, [here](https://github.com/tektoncd/operator/blob/1406b846022e92f4ac15ec695fb94a1b7b12a221/pkg/reconciler/shared/tektonconfig/trigger/trigger.go#L34).

The use of polling makes debugging harder and it could be the source of tricky bugs. 

This issue is created as a tracker to track this refactoring. 🧑‍💻

**Comment by savitaashture** [comment]
I think we need same changes for Dashboard as well
