### ISSUE TITLE
Add e2e test for upgrade scenario

### ISSUE THREAD

**Issue by sm43** [tektoncd/operator#762]
Currently we don't have any test for upgrades
we only install the a version and check if all components are ready.
we need to add test for upgrade.

**Comment by sm43** [comment]
probable solution as discussed in WG
```
Install the latest release operator version, 
Let it bring up all components
Then uninstall previous operator releases without deletion what operator installed
Then install current build
Wait for it to become successful and alive
```

**Comment by savitaashture** [comment]
WG discussion point

1. Install latest release version
2. Upgarde from PR commit
3. Run e2e to verify successful upgradation

**Comment by vdemeester** [comment]
We should probably try to use `kind` for this https://github.com/tektoncd/plumbing/blob/d765a5cba75fe5c3d4b67b8651caf72e704a22dc/tekton/images/kind-e2e/setup-kind.sh
