### ISSUE TITLE
perilaku yang diharapkan 

### ISSUE THREAD

**Issue by AriesTriputranto9** [tektoncd/operator#770]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1. Optional
2. Optional
3. Optional

# Additional Info

- Kubernetes version: optional

  **Output of `kubectl version`:**

  ``` optional
  (Optional)
  ```

- Tekton Pipeline version:
   Optional
  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

[tekton](https://tekton.dev)

**Comment by nikhil-thomas** [comment]
@AriesTriputranto9 i am assuming this issue was posted before it was wrote down. 

Could you either add necessary details or close this issue. 🧑‍💻
