### ISSUE TITLE
Eliminate the explicit dependency between components enforced by operator

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/operator#784]
# Description

At present, operator enforces an explicit dependency between components during installation and upgrades. For example, TektonTrigger reconciler will install Tektoncd Triggers only if the operaotor can verify that Tektoncd Pipelines is already installed by the operator (checks for TektonPipeline instance status). In the case of OpenShift, TektonAddon installation waits till TektonPipeline and TektonTriggers are installed.

These explicit blocking of component installation creates unnecessary delays in the installation process. We loose the oportunity to run each reconciler in a truly parallel sense.

 In my opinion, if we eliminate this dependency and move such validations in to a common point, we can make the operator faster and the ux more smooth.

For example, we can move validations to the end of TektonConfig reconciler from various other reconcilers. In addition, TektonConfig reconciler is the one who is aware of "Profiles" or the list of components being installed. 

# Challenges and Possible Solutions to Tackle them

1. TektonAddon (in OpenShift) has a real dependency on Pipelines and Triggers as operator won't be able to create ClusterTasks and ClusterTriggerBindings from TektonAddon if Pipeline and Triggers are not installed

One way to handle this situation will be to move the installation of "Addons" like clusterTasks to the "PostReconcie" of appropriate reconciler. For example, we can make OpenShift extension for TektonPipeline reconciler handle installation of ClusterTasks.

**Comment by nikhil-thomas** [comment]
cc @concaf

**Comment by concaf** [comment]
I think that a prerequisite before starting this would be to analyze all the components on a case-to-case basis on what their behavior is when the dependency is not present (and possibly establish a project wide consensus/standard on how cases like this (dependency missing) are handled)
