### ISSUE TITLE
buildah clustertask uses restricted rhel8 image

### ISSUE THREAD

**Issue by ibotty** [tektoncd/operator#785]
# Expected Behavior

buildah clustertask works and uses the `quay.io/buildah/stable` image by default.

# Actual Behavior
The pod cannot run because it cannot pull the default image due to (intentional) missing pull credentials for redhat registry.

- Tekton Pipeline version
```
Client version: 0.23.1
Pipeline version: v0.35.0
Triggers version: v0.19.1
Operator version: v0.57.0
```

**Comment by piyush-garg** [comment]
We need the change the default image for upstream, and replace it via csv generation mechanism for downstream

**Comment by vdemeester** [comment]
Note that the ClusterTask are deprecated and long term, they will removed from the operator. But reopening for now.
