### ISSUE TITLE
Handle changes of labels in pipeline, triggers and dashboard deployments

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/operator#88]
# Expected Behavior
The latest pipeline, triggers and dashboard can be updated to the latest release

# Actual Behavior
The master version of the three projects failed to update the in the `robocat` cluster because of new labels that were added to the deployments, which cause errors during update of the existing deployments:

```
[deploy-tekton-project] Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
[deploy-tekton-project] Name: "tekton-pipelines-webhook", Namespace: "tekton-pipelines"
[deploy-tekton-project] for: "pipeline/overlays/robocat": Deployment.apps "tekton-pipelines-webhook" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"webhook", "app.kubernetes.io/instance":"default", "app.kubernetes.io/name":"webhook", "app.kubernetes.io/part-of":"tekton-pipelines"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

```

This is a heads-up as the operator may have to deal with this to ensure seamless upgrade.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info
See https://github.com/tektoncd/plumbing/issues/392 for more details

**Comment by nikhil-thomas** [comment]
definitely, these are the typical use cases were the operator adds value.

**Comment by vincent-pli** [comment]
https://github.com/manifestival/manifestival/pull/51

**Comment by vincent-pli** [comment]
@sthaha Are you still work on this issue?

**Comment by sthaha** [comment]
@vincent-pli , @nikhil-thomas  my plan was to have this issue fixed while making the release. We may still want to do that for this release we are trying to make.

**Comment by vincent-pli** [comment]
@sthaha 
The `jcrossley3/manifestival` has been archived, the new repo is: [github.com/manifestival/manifestival](https://github.com/manifestival/manifestival)
I think we need to upgrade to the new one.

BTW, seems the PR I mentioned in the comments is not be accepted, so we need implement it ourselves, then need depends on the new features introduced by `github.com/manifestival/manifestival`.
Any comments?
