### ISSUE TITLE
how can i get images in china

### ISSUE THREAD

**Issue by r67yfyt** [tektoncd/operator#908]
# Expected Behavior
i can easily get images include operator, pipeline, dashboard, chain, etc;
how can i customize all images, now i can only edit operator images in the release file, not the other CR images!!!
# Actual Behavior
we can't acess gcr.io and ghcr.io;
# Steps to Reproduce the Problem

1. install with operator helm chart
2. fail to download image

**Comment by nikhil-thomas** [comment]
There is one way. We can do this be specifying image overrides as environment variables in the operator controller deployment. refer #610

**Comment by r67yfyt** [comment]
how can i deal with helm chart?

**Comment by lookis** [comment]
@r67yfyt if you have a proxy server, you can try these setup: https://zhuanlan.zhihu.com/p/545327043

**Comment by r67yfyt** [comment]
> @r67yfyt if you have a proxy server, you can try these setup: https://zhuanlan.zhihu.com/p/545327043

product enviroment cannot set proxy
